// REF: https://learn.microsoft.com/en-us/powershell/module/teams/new-csteamsmeetingpolicy?view=teams-ps
package teamsMeetingPolicy

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type TeamsMeetingPolicyResourceModel struct {
	ID                                          types.String `tfsdk:"id"`
	XdsIdentity                                 types.String `tfsdk:"xds_identity"`
	AIInterpreter                               types.String `tfsdk:"ai_interpreter"`
	AllowAnnotations                            types.Bool   `tfsdk:"allow_annotations"`
	AllowAnonymousUsersToDialOut                types.Bool   `tfsdk:"allow_anonymous_users_to_dial_out"`
	AllowAnonymousUsersToJoinMeeting            types.Bool   `tfsdk:"allow_anonymous_users_to_join_meeting"`
	AllowAnonymousUsersToStartMeeting           types.Bool   `tfsdk:"allow_anonymous_users_to_start_meeting"`
	AllowAvatarsInGallery                       types.Bool   `tfsdk:"allow_avatars_in_gallery"`
	AllowBreakoutRooms                          types.Bool   `tfsdk:"allow_breakout_rooms"`
	AllowCarbonSummary                          types.Bool   `tfsdk:"allow_carbon_summary"`
	AllowCartCaptionsScheduling                 types.String `tfsdk:"allow_cart_captions_scheduling"`
	AllowChannelMeetingScheduling               types.Bool   `tfsdk:"allow_channel_meeting_scheduling"`
	AllowCloudRecording                         types.Bool   `tfsdk:"allow_cloud_recording"`
	AllowDocumentCollaboration                  types.String `tfsdk:"allow_document_collaboration"`
	AllowEngagementReport                       types.String `tfsdk:"allow_engagement_report"`
	AllowExternalNonTrustedMeetingChat          types.Bool   `tfsdk:"allow_external_non_trusted_meeting_chat"`
	AllowExternalParticipantGiveRequestControl  types.Bool   `tfsdk:"allow_external_participant_give_request_control"`
	AllowImmersiveView                          types.Bool   `tfsdk:"allow_immersive_view"`
	AllowIPAudio                                types.Bool   `tfsdk:"allow_ip_audio"`
	AllowIPVideo                                types.Bool   `tfsdk:"allow_ip_video"`
	AllowLocalRecording                         types.Bool   `tfsdk:"allow_local_recording"`
	AllowMeetingCoach                           types.Bool   `tfsdk:"allow_meeting_coach"`
	AllowMeetNow                                types.Bool   `tfsdk:"allow_meet_now"`
	AllowMeetingReactions                       types.Bool   `tfsdk:"allow_meeting_reactions"`
	AllowMeetingRegistration                    types.Bool   `tfsdk:"allow_meeting_registration"`
	AllowNDIStreaming                           types.Bool   `tfsdk:"allow_ndi_streaming"`
	AllowNetworkConfigurationSettingsLookup     types.Bool   `tfsdk:"allow_network_configuration_settings_lookup"`
	AllowOrganizersToOverrideLobbySettings      types.Bool   `tfsdk:"allow_organizers_to_override_lobby_settings"`
	AllowOutlookAddIn                           types.Bool   `tfsdk:"allow_outlook_add_in"`
	AllowPSTNUsersToBypassLobby                 types.Bool   `tfsdk:"allow_pstn_users_to_bypass_lobby"`
	AllowParticipantGiveRequestControl          types.Bool   `tfsdk:"allow_participant_give_request_control"`
	AllowPowerPointSharing                      types.Bool   `tfsdk:"allow_power_point_sharing"`
	AllowPrivateMeetNow                         types.Bool   `tfsdk:"allow_private_meet_now"`
	AllowPrivateMeetingScheduling               types.Bool   `tfsdk:"allow_private_meeting_scheduling"`
	AllowRecordingStorageOutsideRegion          types.Bool   `tfsdk:"allow_recording_storage_outside_region"`
	AllowScreenContentDigitization              types.Bool   `tfsdk:"allow_screen_content_digitization"`
	AllowSharedNotes                            types.Bool   `tfsdk:"allow_shared_notes"`
	AllowTasksFromTranscript                    types.String `tfsdk:"allow_tasks_from_transcript"`
	AllowTrackingInReport                       types.Bool   `tfsdk:"allow_tracking_in_report"`
	AllowTranscription                          types.Bool   `tfsdk:"allow_transcription"`
	AllowedUsersForMeetingContext               types.String `tfsdk:"allowed_users_for_meeting_context"`
	AllowUserToJoinExternalMeeting              types.String `tfsdk:"allow_user_to_join_external_meeting"`
	AllowWatermarkCustomizationForCameraVideo   types.Bool   `tfsdk:"allow_watermark_customization_for_camera_video"`
	AllowWatermarkCustomizationForScreenSharing types.Bool   `tfsdk:"allow_watermark_customization_for_screen_sharing"`
	AllowWatermarkForCameraVideo                types.Bool   `tfsdk:"allow_watermark_for_camera_video"`
	AllowWatermarkForScreenSharing              types.Bool   `tfsdk:"allow_watermark_for_screen_sharing"`
	AllowWhiteboard                             types.Bool   `tfsdk:"allow_whiteboard"`
	AllowedStreamingMediaInput                  types.String `tfsdk:"allowed_streaming_media_input"`
	AnonymousUserAuthenticationMethod           types.String `tfsdk:"anonymous_user_authentication_method"`
	AttendeeIdentityMasking                     types.String `tfsdk:"attendee_identity_masking"`
	AudibleRecordingNotification                types.String `tfsdk:"audible_recording_notification"`
	AutoAdmittedUsers                           types.String `tfsdk:"auto_admitted_users"`
	AutoRecording                               types.String `tfsdk:"auto_recording"`
	AutomaticallyStartCopilot                   types.String `tfsdk:"automatically_start_copilot"`
	BlockedAnonymousJoinClientTypes             types.List   `tfsdk:"blocked_anonymous_join_client_types"`
	CaptchaVerificationForMeetingJoin           types.String `tfsdk:"captcha_verification_for_meeting_join"`
	ChannelRecordingDownload                    types.String `tfsdk:"channel_recording_download"`
	ConnectToMeetingControls                    types.String `tfsdk:"connect_to_meeting_controls"`
	ContentSharingInExternalMeetings            types.String `tfsdk:"content_sharing_in_external_meetings"`
	Copilot                                     types.String `tfsdk:"copilot"`
	CopyRestriction                             types.Bool   `tfsdk:"copy_restriction"`
	Description                                 types.String `tfsdk:"description"`
	DesignatedPresenterRoleMode                 types.String `tfsdk:"designated_presenter_role_mode"`
	DetectSensitiveContentDuringScreenSharing   types.Bool   `tfsdk:"detect_sensitive_content_during_screen_sharing"`
	EnrollUserOverride                          types.String `tfsdk:"enroll_user_override"`
	ExplicitRecordingConsent                    types.String `tfsdk:"explicit_recording_consent"`
	ExternalMeetingJoin                         types.String `tfsdk:"external_meeting_join"`
	InfoShownInReportMode                       types.String `tfsdk:"info_shown_in_report_mode"`
	IPAudioMode                                 types.String `tfsdk:"ip_audio_mode"`
	IPVideoMode                                 types.String `tfsdk:"ip_video_mode"`
	LiveCaptionsEnabledType                     types.String `tfsdk:"live_captions_enabled_type"`
	LiveInterpretationEnabledType               types.String `tfsdk:"live_interpretation_enabled_type"`
	LiveStreamingMode                           types.String `tfsdk:"live_streaming_mode"`
	LobbyChat                                   types.String `tfsdk:"lobby_chat"`
	MediaBitRateKb                              types.Int64  `tfsdk:"media_bit_rate_kb"`
	MeetingChatEnabledType                      types.String `tfsdk:"meeting_chat_enabled_type"`
	MeetingInviteLanguages                      types.String `tfsdk:"meeting_invite_languages"`
	NewMeetingRecordingExpirationDays           types.Int64  `tfsdk:"new_meeting_recording_expiration_days"`
	NoiseSuppressionForDialInParticipants       types.String `tfsdk:"noise_suppression_for_dial_in_participants"`
	ParticipantNameChange                       types.String `tfsdk:"participant_name_change"`
	PreferredMeetingProviderForIslandsMode      types.String `tfsdk:"preferred_meeting_provider_for_islands_mode"`
	QnAEngagementMode                           types.String `tfsdk:"qna_engagement_mode"`
	RecordingStorageMode                        types.String `tfsdk:"recording_storage_mode"`
	RoomAttributeUserOverride                   types.String `tfsdk:"room_attribute_user_override"`
	RoomPeopleNameUserOverride                  types.String `tfsdk:"room_people_name_user_override"`
	ScreenSharingMode                           types.String `tfsdk:"screen_sharing_mode"`
	SmsNotifications                            types.String `tfsdk:"sms_notifications"`
	SpeakerAttributionMode                      types.String `tfsdk:"speaker_attribution_mode"`
	StreamingAttendeeMode                       types.String `tfsdk:"streaming_attendee_mode"`
	TeamsCameraFarEndPTZMode                    types.String `tfsdk:"teams_camera_far_end_ptz_mode"`
	Tenant                                      types.String `tfsdk:"tenant"`
	UsersCanAdmitFromLobby                      types.String `tfsdk:"users_can_admit_from_lobby"`
	VideoFiltersMode                            types.String `tfsdk:"video_filters_mode"`
	VoiceIsolation                              types.String `tfsdk:"voice_isolation"`
	VoiceSimulationInInterpreter                types.String `tfsdk:"voice_simulation_in_interpreter"`
	WatermarkForAnonymousUsers                  types.String `tfsdk:"watermark_for_anonymous_users"`
	WatermarkForCameraVideoOpacity              types.Int64  `tfsdk:"watermark_for_camera_video_opacity"`
	WatermarkForCameraVideoPattern              types.String `tfsdk:"watermark_for_camera_video_pattern"`
	WatermarkForScreenSharingOpacity            types.Int64  `tfsdk:"watermark_for_screen_sharing_opacity"`
	WatermarkForScreenSharingPattern            types.String `tfsdk:"watermark_for_screen_sharing_pattern"`
	AllowedUsersForMeetingDetails               types.String `tfsdk:"allowed_users_for_meeting_details"`
	RealTimeText                                types.String `tfsdk:"real_time_text"`
	ParticipantSlideControl                     types.String `tfsdk:"participant_slide_control"`
	WhoCanRegister                              types.String `tfsdk:"who_can_register"`
}
