# Import the tenant-wide external identities policy using its fixed singleton ID.
terraform import microsoft365_graph_beta_identity_and_access_external_identities_policy.example externalIdentityPolicy
