version: '0.19'

formatter: markdown

output:
  file: README.md
  mode: inject
  template: |
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  indent: 3
  escape: false
  anchor: true
  provider:
    name: microsoft365
    registry_hostname: registry.terraform.io
    source: deploymenttheory/microsoft365

templates:
  data_source: templates/data_sources.md.tmpl
  resource: templates/resources.md.tmpl
  index: templates/index.md.tmpl