resource "microsoft365_graph_beta_device_and_app_management_android_managed_device_app_configuration_policy" "microsoft_edge_browser_maximal" {
  display_name         = "unit-test-android-managed-device-app-configuration-policy-microsoft-edge-browser-maximal"
  description          = ""
  targeted_mobile_apps = ["57eb943a-1542-4c9b-b220-ed09b95a50a2"]
  role_scope_tag_ids   = ["0"]

  package_id = "app:com.microsoft.emmx"
  payload_json = jsonencode({
    "kind" : "androidenterprise#managedConfiguration",
    "productId" : "app:com.microsoft.emmx",
    "managedProperty" : [
      { "key" : "EdgeShowBottomBarInKioskMode", "valueBool" : false },
      { "key" : "EdgeShowAddressBarInKioskMode", "valueBool" : false },
      { "key" : "EdgeRestoreBrowsingOption", "valueInteger" : 1 },
      { "key" : "EdgeNewTabPageLayoutUserSelectable", "valueBool" : true },
      { "key" : "EdgeNewTabPageLayoutCustom", "valueString" : "thing" },
      { "key" : "EdgeNewTabPageLayout", "valueString" : "thing" },
      { "key" : "EdgeMyApps", "valueBool" : false },
      { "key" : "EdgeLockedViewModeEnabled", "valueBool" : false },
      { "key" : "EdgeLockedViewModeAllowedActions", "valueString" : "thing" },
      { "key" : "EdgeEnableKioskMode", "valueBool" : false },
      { "key" : "EdgeDisabledFeatures", "valueString" : "thing" },
      { "key" : "EdgeDisableShareUsageData", "valueBool" : false },
      { "key" : "EdgeDisableShareBrowsingHistory", "valueBool" : true },
      { "key" : "EdgeDefaultHTTPS", "valueBool" : false },
      { "key" : "EdgeBrandLogo", "valueBool" : true },
      { "key" : "EdgeBrandColor", "valueBool" : false },
      { "key" : "com.microsoft.intune.mam.AllowedAccountUPNs", "valueString" : "thing" },
      { "key" : "WebUsbBlockedForUrls", "valueString" : "thing" },
      { "key" : "WebUsbAskForUrls", "valueString" : "thing" },
      { "key" : "WebUsbAllowDevicesForUrls", "valueString" : "thing" },
      { "key" : "WebRtcUdpPortRange", "valueString" : "thing" },
      { "key" : "WebAuthenticationRemoteDesktopAllowedOrigins", "valueString" : "thing" },
      { "key" : "VirtualKeyboardResizesLayoutByDefault", "valueBool" : false },
      { "key" : "URLBlocklist", "valueString" : "thing" },
      { "key" : "URLAllowlist", "valueString" : "thing" },
      { "key" : "TranslateEnabled", "valueBool" : false },
      { "key" : "SyncDisabled", "valueBool" : false },
      { "key" : "SmartScreenEnabled", "valueBool" : false },
      { "key" : "ServiceWorkerToControlSrcdocIframeEnabled", "valueBool" : false },
      { "key" : "SensorsBlockedForUrls", "valueString" : "thing" },
      { "key" : "SensorsAllowedForUrls", "valueString" : "thing" },
      { "key" : "SearchSuggestEnabled", "valueBool" : false },
      { "key" : "ScrollToTextFragmentEnabled", "valueBool" : false },
      { "key" : "SavingBrowserHistoryDisabled", "valueBool" : false },
      { "key" : "SSLErrorOverrideAllowedForOrigins", "valueString" : "thing" },
      { "key" : "SSLErrorOverrideAllowed", "valueBool" : false },
      { "key" : "RelatedWebsiteSetsOverrides", "valueString" : "thing" },
      { "key" : "RelatedWebsiteSetsEnabled", "valueBool" : false },
      { "key" : "ReduceAcceptLanguageEnabled", "valueBool" : false },
      { "key" : "QRCodeGeneratorEnabled", "valueBool" : false },
      { "key" : "ProxySettings", "valueString" : "thing" },
      { "key" : "PromptForDownloadLocation", "valueBool" : false },
      { "key" : "PrintingEnabled", "valueBool" : false },
      { "key" : "PostQuantumKeyAgreementEnabled", "valueBool" : false },
      { "key" : "PopupsBlockedForUrls", "valueString" : "thing" },
      { "key" : "PopupsAllowedForUrls", "valueString" : "thing" },
      { "key" : "PaymentMethodQueryEnabled", "valueBool" : false },
      { "key" : "PasswordManagerEnabled", "valueBool" : false },
      { "key" : "PartitionedBlobUrlUsage", "valueBool" : false },
      { "key" : "OverrideSecurityRestrictionsOnInsecureOrigin", "valueString" : "thing" },
      { "key" : "OverlayPermissionDetectionEnabled", "valueBool" : false },
      { "key" : "NtlmV2Enabled", "valueBool" : false },
      { "key" : "NewTabPageLocation", "valueString" : "thing" },
      { "key" : "NetworkPredictionOptions", "valueString" : "0" },
      { "key" : "MobileSiteForceForUrls", "valueString" : "thing" },
      { "key" : "ManagedFavorites", "valueString" : "thing" },
      { "key" : "JavaScriptOptimizerBlockedForSites", "valueString" : "thing" },
      { "key" : "JavaScriptOptimizerAllowedForSites", "valueString" : "thing" },
      { "key" : "JavaScriptJitBlockedForSites", "valueString" : "thing" },
      { "key" : "JavaScriptJitAllowedForSites", "valueString" : "thing" },
      { "key" : "JavaScriptBlockedForUrls", "valueString" : "thing" },
      { "key" : "JavaScriptAllowedForUrls", "valueString" : "thing" },
      { "key" : "InPrivateModeAvailability", "valueString" : "0" },
      { "key" : "ImportPasswordsDisabled", "valueBool" : false },
      { "key" : "IdleTimeoutActions", "valueStringArray" : ["close_browsers", "clear_browsing_history", "clear_download_history", "clear_cookies_and_other_site_data", "clear_cached_images_and_files", "clear_password_signin", "clear_autofill", "clear_site_settings", "reload_pages", "close_tabs"] },
      { "key" : "IdleTimeout", "valueInteger" : 1 },
      { "key" : "IPv6ReachabilityOverrideEnabled", "valueBool" : false },
      { "key" : "HttpsOnlyMode", "valueString" : "allowed" },
      { "key" : "HttpAllowlist", "valueString" : "thing" },
      { "key" : "HideFirstRunExperience", "valueBool" : false },
      { "key" : "HappyEyeballsV3Enabled", "valueBool" : false },
      { "key" : "HSTSPolicyBypassList", "valueString" : "thing" },
      { "key" : "ForceYouTubeRestrict", "valueString" : "1" },
      { "key" : "ForcePermissionPolicyUnloadDefaultEnabled", "valueBool" : false },
      { "key" : "ForceGoogleSafeSearch", "valueBool" : false },
      { "key" : "ExtensionSettings", "valueString" : "thing" },
      { "key" : "ExperimentationAndConfigurationServiceControl", "valueString" : "0" },
      { "key" : "EncryptedClientHelloEnabled", "valueBool" : false },
      { "key" : "EnableMediaRouter", "valueBool" : false },
      { "key" : "EditFavoritesEnabled", "valueBool" : false },
      { "key" : "EdgeSharedDeviceSupportEnabled", "valueBool" : false },
      { "key" : "EdgeOneAuthProxy", "valueString" : "thing" },
      { "key" : "EdgeCopilotEnabled", "valueBool" : false },
      { "key" : "EdgeBlockSignInEnabled", "valueBool" : false },
      { "key" : "EdgeAllowedAccountUPN", "valueString" : "thing" },
      { "key" : "EdgeAllowedAccountOnly", "valueBool" : false },
      { "key" : "DownloadRestrictions", "valueString" : "1" },
      { "key" : "DisabledMiniApps", "valueStringArray" : ["featured_feature", "sydney_chat", "download_manager", "pdf_reader", "news_feed", "translator", "converter", "money", "images", "covid", "games", "deals", "wallet", "weather", "gaokao", "weather_etree", "weather_map", "weather_life"] },
      { "key" : "DisableAuthNegotiateCnameLookup", "valueBool" : false },
      { "key" : "DesktopSiteForceForUrls", "valueString" : "thing" },
      { "key" : "DefaultWebUsbGuardSetting", "valueString" : "2" },
      { "key" : "DefaultWebBluetoothGuardSetting", "valueString" : "3" },
      { "key" : "DefaultSensorsSetting", "valueString" : "1" },
      { "key" : "DefaultSearchProviderSuggestURL", "valueString" : "thing" },
      { "key" : "DefaultSearchProviderSearchURL", "valueString" : "thing" },
      { "key" : "DefaultSearchProviderName", "valueString" : "thing" },
      { "key" : "DefaultSearchProviderImageURLPostParams", "valueString" : "thing" },
      { "key" : "DefaultSearchProviderImageURL", "valueString" : "thing" },
      { "key" : "DefaultSearchProviderEncodings", "valueString" : "thing" },
      { "key" : "DefaultSearchProviderEnabled", "valueBool" : false },
      { "key" : "DefaultPopupsSetting", "valueString" : "1" },
      { "key" : "DefaultJavaScriptSetting", "valueString" : "1" },
      { "key" : "DefaultJavaScriptOptimizerSetting", "valueString" : "1" },
      { "key" : "DefaultJavaScriptJitSetting", "valueString" : "2" },
      { "key" : "DefaultGeolocationSetting", "valueString" : "2" },
      { "key" : "DefaultDesktopSiteSetting", "valueString" : "2" },
      { "key" : "DefaultCookiesSetting", "valueString" : "4" },
      { "key" : "DefaultBrowserSettingEnabled", "valueBool" : false },
      { "key" : "DataUrlInSvgUseEnabled", "valueBool" : false },
      { "key" : "DataURLWhitespacePreservationEnabled", "valueBool" : false },
      { "key" : "CookiesSessionOnlyForUrls", "valueString" : "thing" },
      { "key" : "CookiesBlockedForUrls", "valueString" : "thing" },
      { "key" : "CookiesAllowedForUrls", "valueString" : "thing" },
      { "key" : "CertificateTransparencyEnforcementDisabledForUrls", "valueString" : "thing" },
      { "key" : "CertificateTransparencyEnforcementDisabledForCas", "valueString" : "thing" },
      { "key" : "CORSNonWildcardRequestHeadersSupport", "valueBool" : false },
      { "key" : "CAPlatformIntegrationEnabled", "valueBool" : false },
      { "key" : "CAHintCertificates", "valueString" : "thing" },
      { "key" : "CADistrustedCertificates", "valueString" : "thing" },
      { "key" : "CACertificatesWithConstraints", "valueString" : "thing" },
      { "key" : "CACertificates", "valueString" : "thing" },
      { "key" : "BuiltInDnsClientEnabled", "valueBool" : false },
      { "key" : "BlockThirdPartyCookies", "valueBool" : false },
      { "key" : "BiometricAuthenticationBeforeFilling", "valueBool" : false },
      { "key" : "BackForwardCacheEnabled", "valueBool" : false },
      { "key" : "AutofillCreditCardEnabled", "valueBool" : false },
      { "key" : "AutofillAddressEnabled", "valueBool" : false },
      { "key" : "AuthServerAllowlist", "valueString" : "thing" },
      { "key" : "AuthSchemes", "valueString" : "thing" },
      { "key" : "AuthNegotiateDelegateAllowlist", "valueString" : "thing" },
      { "key" : "AuthAndroidNegotiateAccountType", "valueString" : "thing" },
      { "key" : "AlternateErrorPagesEnabled", "valueBool" : false },
      { "key" : "AllowedDomainsForApps", "valueString" : "thing" },
      { "key" : "AllowWebAuthnWithBrokenTlsCerts", "valueBool" : false },
      { "key" : "AllowBackForwardCacheForCacheControlNoStorePageEnabled", "valueBool" : false },
      { "key" : "AllHttpAuthSchemesAllowedForOrigins", "valueString" : "thing" },
      { "key" : "AddressBarWorkSearchResultsEnabled", "valueBool" : false },
      { "key" : "AdditionalDnsQueryTypesEnabled", "valueBool" : false },
      { "key" : "AccessibilityPerformanceFilteringAllowed", "valueBool" : false },
      { "key" : "AccessControlAllowMethodsInCORSPreflightSpecConformant", "valueBool" : false }
    ]
  })
  profile_applicability  = "androidWorkProfile"
  connected_apps_enabled = true

  permission_actions = [
    { permission = "android.permission-group.NEARBY_DEVICES", action = "prompt" },
    { permission = "android.permission.NEARBY_WIFI_DEVICES", action = "prompt" },
    { permission = "android.permission.BLUETOOTH_CONNECT", action = "prompt" },
    { permission = "android.permission.READ_MEDIA_AUDIO", action = "prompt" },
    { permission = "android.permission.READ_MEDIA_IMAGES", action = "prompt" },
    { permission = "android.permission.READ_MEDIA_VIDEO", action = "prompt" },
    { permission = "android.permission.POST_NOTIFICATIONS", action = "prompt" },
    { permission = "android.permission.WRITE_EXTERNAL_STORAGE", action = "prompt" },
    { permission = "android.permission.READ_EXTERNAL_STORAGE", action = "prompt" },
    { permission = "android.permission.RECEIVE_MMS", action = "prompt" },
    { permission = "android.permission.RECEIVE_WAP_PUSH", action = "prompt" },
    { permission = "android.permission.READ_SMS", action = "prompt" },
    { permission = "android.permission.RECEIVE_SMS", action = "prompt" },
    { permission = "android.permission.SEND_SMS", action = "prompt" },
    { permission = "android.permission.BODY_SENSORS_BACKGROUND", action = "prompt" },
    { permission = "android.permission.BODY_SENSORS", action = "prompt" },
    { permission = "android.permission.PROCESS_OUTGOING_CALLS", action = "prompt" },
    { permission = "android.permission.USE_SIP", action = "prompt" },
    { permission = "android.permission.ADD_VOICEMAIL", action = "prompt" },
    { permission = "android.permission.WRITE_CALL_LOG", action = "prompt" },
    { permission = "android.permission.READ_CALL_LOG", action = "prompt" },
    { permission = "android.permission.CALL_PHONE", action = "prompt" },
    { permission = "android.permission.READ_PHONE_STATE", action = "prompt" },
    { permission = "android.permission.RECORD_AUDIO", action = "prompt" },
    { permission = "android.permission.ACCESS_BACKGROUND_LOCATION", action = "prompt" },
    { permission = "android.permission.ACCESS_COARSE_LOCATION", action = "prompt" },
    { permission = "android.permission.ACCESS_FINE_LOCATION", action = "prompt" },
    { permission = "android.permission.GET_ACCOUNTS", action = "prompt" },
    { permission = "android.permission.WRITE_CONTACTS", action = "prompt" },
    { permission = "android.permission.READ_CONTACTS", action = "prompt" },
    { permission = "android.permission.CAMERA", action = "prompt" },
    { permission = "android.permission.WRITE_CALENDAR", action = "prompt" },
    { permission = "android.permission.READ_CALENDAR", action = "prompt" }
  ]
}

