# Token signing certificate generated by Microsoft Entra for SAML single sign-on.
# Combine with the preferred token signing key thumbprint resource to activate it.

resource "microsoft365_graph_beta_applications_application" "example" {
  display_name     = "Example SAML Application"
  sign_in_audience = "AzureADMyOrg"
}

resource "microsoft365_graph_beta_applications_service_principal" "example" {
  app_id                        = microsoft365_graph_beta_applications_application.example.app_id
  preferred_single_sign_on_mode = "saml"
}

resource "microsoft365_graph_beta_applications_service_principal_token_signing_certificate" "example" {
  service_principal_id = microsoft365_graph_beta_applications_service_principal.example.id
  display_name         = "CN=Example SAML Signing"
  end_date_time        = "2028-01-01T14:59:59Z"

  # Create the replacement certificate before destroying the old one so the
  # preferred token signing key thumbprint can be rotated without downtime.
  lifecycle {
    create_before_destroy = true
  }
}

resource "microsoft365_graph_beta_applications_service_principal_preferred_token_signing_key_thumbprint" "example" {
  service_principal_id = microsoft365_graph_beta_applications_service_principal.example.id
  thumbprint           = microsoft365_graph_beta_applications_service_principal_token_signing_certificate.example.thumbprint
}
