resource "microsoft365_graph_beta_device_and_app_management_android_managed_device_app_configuration_policy" "managed_home_screen_maximal" {
  display_name         = "acc-test-android-managed-device-app-configuration-policy-managed-home-screen-maximal"
  description          = ""
  targeted_mobile_apps = ["86263173-c38d-491f-b090-b2a9dbfeb09f"]
  role_scope_tag_ids   = ["0"]

  package_id = "app:com.microsoft.launcher.enterprise"
  payload_json = jsonencode({
    "kind" : "androidenterprise#managedConfiguration",
    "productId" : "app:com.microsoft.launcher.enterprise",
    "managedProperty" : [
      { "key" : "offline_work_time_before_required_sign_in", "valueInteger" : 60 },
      { "key" : "show_alarm_volume_control", "valueBool" : false },
      { "key" : "show_notification_volume_control", "valueBool" : false },
      { "key" : "show_ring_volume_control", "valueBool" : false },
      { "key" : "show_call_volume_control", "valueBool" : false },
      { "key" : "show_ringtone_selector", "valueBool" : false },
      { "key" : "show_autorotate_toggle", "valueBool" : false },
      { "key" : "show_brightness_slider", "valueBool" : false },
      { "key" : "show_adaptive_brightness_toggle", "valueBool" : false },
      { "key" : "minimum_inactive_time_before_session_pin_required", "valueInteger" : 0 },
      { "key" : "header_name_style", "valueString" : "Display Name" },
      { "key" : "header_secondary_element", "valueString" : "Serial Number" },
      { "key" : "header_primary_element", "valueString" : "Tenant Name" },
      { "key" : "fixed_time_to_give_user_notice", "valueInteger" : 30 },
      { "key" : "fixed_time_to_signout", "valueInteger" : 12 },
      { "key" : "enable_fixed_signout", "valueBool" : false },
      { "key" : "block_pinning_browser_web_pages_to_MHS", "valueBool" : false },
      { "key" : "amount_of_time_before_try_exit_PIN_again", "valueInteger" : 0 },
      { "key" : "max_number_of_attempts_for_exit_PIN", "valueInteger" : 0 },
      { "key" : "minimum_length_for_session_PIN", "valueInteger" : 1 },
      { "key" : "max_number_of_attempts_for_session_PIN", "valueInteger" : 0 },
      { "key" : "custom_privacy_statement_url", "valueString" : "thing" },
      { "key" : "custom_privacy_statement_title", "valueString" : "thing" },
      { "key" : "enable_language_setting", "valueBool" : false },
      { "key" : "enable_PIN_to_resume", "valueBool" : false },
      { "key" : "auto_signout_time_to_give_user_notice", "valueInteger" : 60 },
      { "key" : "inactive_time_to_signout", "valueInteger" : 300 },
      { "key" : "enable_auto_signout", "valueBool" : false },
      { "key" : "session_PIN_complexity", "valueString" : "simple" },
      { "key" : "enable_session_PIN", "valueBool" : false },
      { "key" : "signin_screen_branding_logo", "valueString" : "thing" },
      { "key" : "enable_corporate_logo", "valueBool" : true },
      { "key" : "signin_screen_wallpaper", "valueString" : "thing" },
      { "key" : "signin_type", "valueString" : "AAD" },
      { "key" : "enable_mhs_signin", "valueBool" : false },
      { "key" : "theme_color", "valueString" : "light" },
      { "key" : "max_absolute_time_outside_MHS", "valueInteger" : 600 },
      { "key" : "max_inactive_time_outside_MHS", "valueInteger" : 180 },
      { "key" : "enable_max_absolute_time_outside_MHS", "valueBool" : false },
      { "key" : "enable_max_inactive_time_outside_MHS", "valueBool" : false },
      { "key" : "enable_easy_access_debugmenu", "valueBool" : false },
      { "key" : "apps_in_folder_ordered_by_name", "valueBool" : true },
      { "key" : "app_order_enabled", "valueBool" : false },
      { "key" : "login_hint_text", "valueString" : "thing" },
      { "key" : "domain_name", "valueString" : "thing" },
      { "key" : "show_device_name", "valueBool" : false },
      { "key" : "show_device_info_setting", "valueBool" : false },
      { "key" : "show_volume_setting", "valueBool" : false },
      { "key" : "show_flashlight_setting", "valueBool" : false },
      { "key" : "show_bluetooth_setting", "valueBool" : false },
      { "key" : "show_managed_setting", "valueBool" : true },
      { "key" : "show_wifi_setting", "valueBool" : false },
      { "key" : "exit_lock_task_mode_code", "valueString" : "thing" },
      { "key" : "show_virtual_status_bar", "valueBool" : false },
      { "key" : "virtual_app_switcher_type", "valueString" : "float" },
      { "key" : "virtual_home_type", "valueString" : "swipe_up" },
      { "key" : "show_virtual_home", "valueBool" : false },
      { "key" : "media_detect_before_screen_saver", "valueBool" : true },
      { "key" : "inactive_time_to_show_screen_saver", "valueInteger" : 30 },
      { "key" : "screen_saver_show_time", "valueInteger" : 0 },
      { "key" : "screen_saver_image", "valueString" : "http://thing" },
      { "key" : "show_screen_saver", "valueBool" : false },
      { "key" : "enable_wifi_allowlist", "valueBool" : false },
      { "key" : "screen_orientation", "valueInteger" : 1 },
      { "key" : "app_folder_icon", "valueInteger" : 0 },
      { "key" : "icon_size", "valueInteger" : 2 },
      { "key" : "wallpaper", "valueString" : "default" },
      { "key" : "lock_home_screen", "valueBool" : true },
      { "key" : "show_notification_badge", "valueBool" : false },
      { "key" : "grid_size", "valueString" : "Auto" }
    ]
  })
  profile_applicability  = "default"
  connected_apps_enabled = true

  permission_actions = [
    { permission = "android.permission-group.NEARBY_DEVICES", action = "prompt" },
    { permission = "android.permission.NEARBY_WIFI_DEVICES", action = "prompt" },
    { permission = "android.permission.BLUETOOTH_CONNECT", action = "prompt" },
    { permission = "android.permission.READ_MEDIA_AUDIO", action = "prompt" },
    { permission = "android.permission.READ_MEDIA_IMAGES", action = "prompt" },
    { permission = "android.permission.READ_MEDIA_VIDEO", action = "prompt" },
    { permission = "android.permission.POST_NOTIFICATIONS", action = "prompt" },
    { permission = "android.permission.WRITE_EXTERNAL_STORAGE", action = "prompt" },
    { permission = "android.permission.READ_EXTERNAL_STORAGE", action = "prompt" },
    { permission = "android.permission.RECEIVE_MMS", action = "prompt" },
    { permission = "android.permission.RECEIVE_WAP_PUSH", action = "prompt" },
    { permission = "android.permission.READ_SMS", action = "prompt" },
    { permission = "android.permission.RECEIVE_SMS", action = "prompt" },
    { permission = "android.permission.SEND_SMS", action = "prompt" },
    { permission = "android.permission.BODY_SENSORS_BACKGROUND", action = "prompt" },
    { permission = "android.permission.BODY_SENSORS", action = "prompt" },
    { permission = "android.permission.PROCESS_OUTGOING_CALLS", action = "prompt" },
    { permission = "android.permission.USE_SIP", action = "prompt" },
    { permission = "android.permission.ADD_VOICEMAIL", action = "prompt" },
    { permission = "android.permission.WRITE_CALL_LOG", action = "prompt" },
    { permission = "android.permission.READ_CALL_LOG", action = "prompt" },
    { permission = "android.permission.CALL_PHONE", action = "prompt" },
    { permission = "android.permission.READ_PHONE_STATE", action = "prompt" },
    { permission = "android.permission.RECORD_AUDIO", action = "prompt" },
    { permission = "android.permission.ACCESS_BACKGROUND_LOCATION", action = "prompt" },
    { permission = "android.permission.ACCESS_COARSE_LOCATION", action = "prompt" },
    { permission = "android.permission.ACCESS_FINE_LOCATION", action = "prompt" },
    { permission = "android.permission.GET_ACCOUNTS", action = "prompt" },
    { permission = "android.permission.WRITE_CONTACTS", action = "prompt" },
    { permission = "android.permission.READ_CONTACTS", action = "prompt" },
    { permission = "android.permission.CAMERA", action = "prompt" },
    { permission = "android.permission.WRITE_CALENDAR", action = "prompt" },
    { permission = "android.permission.READ_CALENDAR", action = "prompt" }
  ]
}

