#!/bin/bash
set -euo pipefail

# Creates GitHub issue and PR for nightly test failures
# Usage: ./handle-failure.sh <owner> <repo> <run-id> <failed-jobs>

OWNER="${1:-}"
REPO="${2:-}"
RUN_ID="${3:-}"
FAILED_JOBS="${4:-}"

if [[ -z "$OWNER" || -z "$REPO" || -z "$RUN_ID" || -z "$FAILED_JOBS" ]]; then
    echo "Usage: $0 <owner> <repo> <run-id> <failed-jobs>"
    echo "Example: $0 deploymenttheory terraform-provider-microsoft365 123456 'Provider-Core,Resources'"
    exit 1
fi

DATE=$(date -u +"%Y-%m-%d")
BRANCH_NAME="nightly-test-failure/${DATE}-${RUN_ID}"
WORKFLOW_URL="https://github.com/${OWNER}/${REPO}/actions/runs/${RUN_ID}"
CODECOV_URL="https://codecov.io/gh/${OWNER}/${REPO}"

echo "Creating failure report for failed jobs: ${FAILED_JOBS}"

# Get default branch
DEFAULT_BRANCH=$(gh api "repos/${OWNER}/${REPO}" --jq '.default_branch')
echo "Default branch: ${DEFAULT_BRANCH}"

# Create new branch
echo "Creating branch: ${BRANCH_NAME}"
gh api "repos/${OWNER}/${REPO}/git/refs/heads/${DEFAULT_BRANCH}" > /tmp/base_ref.json
BASE_SHA=$(jq -r '.object.sha' /tmp/base_ref.json)

gh api "repos/${OWNER}/${REPO}/git/refs" -X POST \
    -f ref="refs/heads/${BRANCH_NAME}" \
    -f sha="${BASE_SHA}" > /dev/null

echo "✅ Created branch: ${BRANCH_NAME}"

# Create FAILURE_REPORT.md
cat > /tmp/FAILURE_REPORT.md <<EOF
# Nightly Test Failure Report

**Date:** ${DATE}
**Workflow Run:** ${RUN_ID}

## Failed Jobs

${FAILED_JOBS}

## Links

- [Workflow Run](${WORKFLOW_URL})
- [Coverage Report](${CODECOV_URL})

## Action Items

- [ ] Investigate test failures
- [ ] Fix failing tests
- [ ] Verify coverage impact
- [ ] Close this PR when resolved

---
🤖 This report was automatically generated by the nightly test failure handler.
EOF

# Commit the file
CONTENT_BASE64=$(base64 -i /tmp/FAILURE_REPORT.md)

gh api "repos/${OWNER}/${REPO}/contents/FAILURE_REPORT.md" -X PUT \
    -f message="chore: nightly test failure report ${DATE}" \
    -f content="${CONTENT_BASE64}" \
    -f branch="${BRANCH_NAME}" > /dev/null

echo "✅ Created FAILURE_REPORT.md"

# Create PR
PR_BODY="## Nightly Test Failure - ${DATE}

**Failed Jobs:** ${FAILED_JOBS}

### Details

This PR was automatically created because nightly tests failed.

**Workflow Run:** ${WORKFLOW_URL}
**Coverage:** ${CODECOV_URL}

### Next Steps

1. Review the [workflow logs](${WORKFLOW_URL})
2. Investigate and fix failing tests
3. Verify coverage hasn't degraded
4. Close this PR when resolved

---
🤖 Generated by nightly test failure handler"

PR_URL=$(gh pr create \
    --repo "${OWNER}/${REPO}" \
    --base "${DEFAULT_BRANCH}" \
    --head "${BRANCH_NAME}" \
    --title "🔴 Nightly Test Failure - ${DATE}" \
    --body "${PR_BODY}" \
    --label "bug,testing,automated,nightly-failure")

echo "✅ Created PR: ${PR_URL}"

# Create Issue
ISSUE_BODY="## Nightly Test Failure - ${DATE}

**Failed Jobs:** ${FAILED_JOBS}

### Links

- **Workflow Run:** ${WORKFLOW_URL}
- **Pull Request:** ${PR_URL}
- **Coverage:** ${CODECOV_URL}

### Action Items

- [ ] Review workflow logs
- [ ] Identify root cause
- [ ] Fix failing tests
- [ ] Verify in PR
- [ ] Monitor next nightly run

---
🤖 Automatically created by nightly test failure handler"

ISSUE_URL=$(gh issue create \
    --repo "${OWNER}/${REPO}" \
    --title "🔴 Nightly Test Failure - ${DATE}" \
    --body "${ISSUE_BODY}" \
    --label "bug,testing,automated,nightly-failure")

echo "✅ Created Issue: ${ISSUE_URL}"

echo ""
echo "Failure handling complete:"
echo "  Branch: ${BRANCH_NAME}"
echo "  PR: ${PR_URL}"
echo "  Issue: ${ISSUE_URL}"
