#!/usr/bin/env python3
"""
Creates GitHub issue and PR for nightly test failures.
Usage: ./report-failure.py <owner> <repo> <run-id> <failed-jobs>
"""

import sys
import json
import subprocess
import base64
from datetime import datetime
from typing import List, Dict


def run_gh_command(args: List[str]) -> str:
    """Run a GitHub CLI command and return output."""
    try:
        result = subprocess.run(
            ["gh"] + args,
            capture_output=True,
            text=True,
            check=True
        )
        return result.stdout.strip()
    except subprocess.CalledProcessError as e:
        print(f"Error running gh command: {e.stderr}", file=sys.stderr)
        raise


def gh_api(endpoint: str, method: str = "GET", data: Dict = None) -> Dict:
    """Make a GitHub API call."""
    cmd = ["api", endpoint]
    
    if method != "GET":
        cmd.extend(["-X", method])
    
    if data:
        for key, value in data.items():
            cmd.extend(["-f", f"{key}={value}"])
    
    result = run_gh_command(cmd)
    return json.loads(result) if result else {}


def main():
    if len(sys.argv) < 5:
        print("Usage: report-failure.py <owner> <repo> <run-id> <failed-jobs>", 
              file=sys.stderr)
        print("Example: report-failure.py deploymenttheory terraform-provider-microsoft365 123456 'Provider-Core,Resources'", 
              file=sys.stderr)
        sys.exit(1)
    
    owner = sys.argv[1]
    repo = sys.argv[2]
    run_id = sys.argv[3]
    failed_jobs = sys.argv[4]
    
    date = datetime.utcnow().strftime("%Y-%m-%d")
    branch_name = f"nightly-test-failure/{date}-{run_id}"
    workflow_url = f"https://github.com/{owner}/{repo}/actions/runs/{run_id}"
    codecov_url = f"https://codecov.io/gh/{owner}/{repo}"
    
    print(f"Creating failure report for failed jobs: {failed_jobs}")
    
    # Get default branch
    repo_info = gh_api(f"repos/{owner}/{repo}")
    default_branch = repo_info["default_branch"]
    print(f"Default branch: {default_branch}")
    
    # Get base SHA
    base_ref = gh_api(f"repos/{owner}/{repo}/git/refs/heads/{default_branch}")
    base_sha = base_ref["object"]["sha"]
    
    # Create new branch
    print(f"Creating branch: {branch_name}")
    gh_api(
        f"repos/{owner}/{repo}/git/refs",
        method="POST",
        data={"ref": f"refs/heads/{branch_name}", "sha": base_sha}
    )
    print(f"✅ Created branch: {branch_name}")
    
    # Create failure report content
    report_content = f"""# Nightly Test Failure Report

**Date:** {date}
**Workflow Run:** {run_id}

## Failed Jobs

{failed_jobs}

## Links

- [Workflow Run]({workflow_url})
- [Coverage Report]({codecov_url})

## Action Items

- [ ] Investigate test failures
- [ ] Fix failing tests
- [ ] Verify coverage impact
- [ ] Close this PR when resolved

---
🤖 This report was automatically generated by the nightly test failure handler.
"""
    
    # Commit the file
    content_base64 = base64.b64encode(report_content.encode()).decode()
    gh_api(
        f"repos/{owner}/{repo}/contents/FAILURE_REPORT.md",
        method="PUT",
        data={
            "message": f"chore: nightly test failure report {date}",
            "content": content_base64,
            "branch": branch_name
        }
    )
    print("✅ Created FAILURE_REPORT.md")
    
    # Create PR
    pr_body = f"""## Nightly Test Failure - {date}

**Failed Jobs:** {failed_jobs}

### Details

This PR was automatically created because nightly tests failed.

**Workflow Run:** {workflow_url}
**Coverage:** {codecov_url}

### Next Steps

1. Review the [workflow logs]({workflow_url})
2. Investigate and fix failing tests
3. Verify coverage hasn't degraded
4. Close this PR when resolved

---
🤖 Generated by nightly test failure handler"""
    
    pr_url = run_gh_command([
        "pr", "create",
        "--repo", f"{owner}/{repo}",
        "--base", default_branch,
        "--head", branch_name,
        "--title", f"🔴 Nightly Test Failure - {date}",
        "--body", pr_body,
        "--label", "bug,testing,automated,nightly-failure"
    ])
    print(f"✅ Created PR: {pr_url}")
    
    # Create Issue
    issue_body = f"""## Nightly Test Failure - {date}

**Failed Jobs:** {failed_jobs}

### Links

- **Workflow Run:** {workflow_url}
- **Pull Request:** {pr_url}
- **Coverage:** {codecov_url}

### Action Items

- [ ] Review workflow logs
- [ ] Identify root cause
- [ ] Fix failing tests
- [ ] Verify in PR
- [ ] Monitor next nightly run

---
🤖 Automatically created by nightly test failure handler"""
    
    issue_url = run_gh_command([
        "issue", "create",
        "--repo", f"{owner}/{repo}",
        "--title", f"🔴 Nightly Test Failure - {date}",
        "--body", issue_body,
        "--label", "bug,testing,automated,nightly-failure"
    ])
    print(f"✅ Created Issue: {issue_url}")
    
    print("\nFailure handling complete:")
    print(f"  Branch: {branch_name}")
    print(f"  PR: {pr_url}")
    print(f"  Issue: {issue_url}")


if __name__ == "__main__":
    main()

