# macOS Device Restrictions.

resource "microsoft365_graph_beta_device_management_device_configuration_templates_json" "macos_device_restrictions" {
  display_name       = "macOS Device Restrictions"
  description        = "Template configuration example"
  role_scope_tag_ids = ["0"]
  settings = jsonencode({
    "@odata.type"                                     = "#microsoft.graph.macOSGeneralDeviceConfiguration"
    "deviceManagementApplicabilityRuleOsEdition"      = null
    "deviceManagementApplicabilityRuleOsVersion"      = null
    "deviceManagementApplicabilityRuleDeviceMode"     = null
    "compliantAppListType"                            = "none"
    "emailInDomainSuffixes"                           = []
    "passwordBlockSimple"                             = false
    "passwordExpirationDays"                          = null
    "passwordMinimumCharacterSetCount"                = null
    "passwordMinimumLength"                           = null
    "passwordMinutesOfInactivityBeforeLock"           = null
    "passwordMinutesOfInactivityBeforeScreenTimeout"  = null
    "passwordPreviousPasswordBlockCount"              = null
    "passwordRequiredType"                            = "deviceDefault"
    "passwordRequired"                                = false
    "passwordMaximumAttemptCount"                     = null
    "passwordMinutesUntilFailedLoginReset"            = null
    "keychainBlockCloudSync"                          = false
    "safariBlockAutofill"                             = false
    "cameraBlocked"                                   = true
    "iTunesBlockMusicService"                         = false
    "spotlightBlockInternetResults"                   = false
    "keyboardBlockDictation"                          = false
    "definitionLookupBlocked"                         = false
    "appleWatchBlockAutoUnlock"                       = false
    "iTunesBlockFileSharing"                          = false
    "iCloudBlockDocumentSync"                         = false
    "iCloudBlockMail"                                 = false
    "iCloudBlockAddressBook"                          = false
    "iCloudBlockCalendar"                             = false
    "iCloudBlockReminders"                            = false
    "iCloudBlockBookmarks"                            = false
    "iCloudBlockNotes"                                = false
    "airDropBlocked"                                  = false
    "passwordBlockModification"                       = false
    "passwordBlockFingerprintUnlock"                  = false
    "passwordBlockAutoFill"                           = false
    "passwordBlockProximityRequests"                  = false
    "passwordBlockAirDropSharing"                     = false
    "softwareUpdatesEnforcedDelayInDays"              = null
    "updateDelayPolicy"                               = null
    "contentCachingBlocked"                           = false
    "iCloudBlockPhotoLibrary"                         = false
    "screenCaptureBlocked"                            = false
    "classroomAppBlockRemoteScreenObservation"        = false
    "classroomAppForceUnpromptedScreenObservation"    = false
    "classroomForceAutomaticallyJoinClasses"          = false
    "classroomForceRequestPermissionToLeaveClasses"   = false
    "classroomForceUnpromptedAppAndDeviceLock"        = false
    "iCloudBlockActivityContinuation"                 = false
    "addingGameCenterFriendsBlocked"                  = false
    "gameCenterBlocked"                               = false
    "multiplayerGamingBlocked"                        = false
    "wallpaperModificationBlocked"                    = false
    "eraseContentAndSettingsBlocked"                  = false
    "softwareUpdateMajorOSDeferredInstallDelayInDays" = null
    "softwareUpdateMinorOSDeferredInstallDelayInDays" = null
    "softwareUpdateNonOSDeferredInstallDelayInDays"   = null
    "touchIdTimeoutInHours"                           = null
    "iCloudPrivateRelayBlocked"                       = false
    "iCloudDesktopAndDocumentsBlocked"                = false
    "activationLockWhenSupervisedAllowed"             = false
    "compliantAppsList"                               = []
    "privacyAccessControls"                           = []
  })
}
