# Complete SAML single sign-on setup with a token signing certificate
# generated by Microsoft Entra and activated via the preferred token
# signing key thumbprint.

resource "microsoft365_graph_beta_applications_application" "example" {
  display_name     = "Example SAML Application"
  sign_in_audience = "AzureADMyOrg"
}

resource "microsoft365_graph_beta_applications_service_principal" "example" {
  app_id                        = microsoft365_graph_beta_applications_application.example.app_id
  preferred_single_sign_on_mode = "saml"
  app_role_assignment_required  = true

  tags = [
    "WindowsAzureActiveDirectoryIntegratedApp",
    "WindowsAzureActiveDirectoryCustomSingleSignOnApplication",
  ]
}

resource "microsoft365_graph_beta_applications_service_principal_token_signing_certificate" "example" {
  service_principal_id = microsoft365_graph_beta_applications_service_principal.example.id
  end_date_time        = "2028-01-01T14:59:59Z"

  lifecycle {
    create_before_destroy = true
  }
}

# Activates the token signing certificate. Rotating the certificate updates
# the thumbprint reference here, which patches the service principal in place.
resource "microsoft365_graph_beta_applications_service_principal_preferred_token_signing_key_thumbprint" "example" {
  service_principal_id = microsoft365_graph_beta_applications_service_principal.example.id
  thumbprint           = microsoft365_graph_beta_applications_service_principal_token_signing_certificate.example.thumbprint
}
