package graphBetaManagedDevice

import (
	"github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/common/convert"
	graphmodels "github.com/microsoftgraph/msgraph-beta-sdk-go/models"
)

// MapRemoteStateToDataSource maps a Windows Managed Device Graph API object to the Terraform model
func MapRemoteStateToDataSource(data graphmodels.ManagedDeviceable) ManagedDeviceDeviceDataItemModel {
	return ManagedDeviceDeviceDataItemModel{
		ID:                                      convert.GraphToFrameworkString(data.GetId()),
		UserId:                                  convert.GraphToFrameworkString(data.GetUserId()),
		DeviceName:                              convert.GraphToFrameworkString(data.GetDeviceName()),
		OwnerType:                               convert.GraphToFrameworkEnum(data.GetOwnerType()),
		ManagedDeviceOwnerType:                  convert.GraphToFrameworkEnum(data.GetManagedDeviceOwnerType()),
		ManagementState:                         convert.GraphToFrameworkEnum(data.GetManagementState()),
		EnrolledDateTime:                        convert.GraphToFrameworkTime(data.GetEnrolledDateTime()),
		LastSyncDateTime:                        convert.GraphToFrameworkTime(data.GetLastSyncDateTime()),
		ChassisType:                             convert.GraphToFrameworkEnum(data.GetChassisType()),
		OperatingSystem:                         convert.GraphToFrameworkString(data.GetOperatingSystem()),
		DeviceType:                              convert.GraphToFrameworkEnum(data.GetDeviceType()),
		ComplianceState:                         convert.GraphToFrameworkEnum(data.GetComplianceState()),
		JailBroken:                              convert.GraphToFrameworkString(data.GetJailBroken()),
		ManagementAgent:                         convert.GraphToFrameworkEnum(data.GetManagementAgent()),
		OSVersion:                               convert.GraphToFrameworkString(data.GetOsVersion()),
		EasActivated:                            convert.GraphToFrameworkBool(data.GetEasActivated()),
		EasDeviceId:                             convert.GraphToFrameworkString(data.GetEasDeviceId()),
		EasActivationDateTime:                   convert.GraphToFrameworkTime(data.GetEasActivationDateTime()),
		AadRegistered:                           convert.GraphToFrameworkBool(data.GetAadRegistered()),
		AzureADRegistered:                       convert.GraphToFrameworkBool(data.GetAzureADRegistered()),
		DeviceEnrollmentType:                    convert.GraphToFrameworkEnum(data.GetDeviceEnrollmentType()),
		LostModeState:                           convert.GraphToFrameworkEnum(data.GetLostModeState()),
		ActivationLockBypassCode:                convert.GraphToFrameworkString(data.GetActivationLockBypassCode()),
		EmailAddress:                            convert.GraphToFrameworkString(data.GetEmailAddress()),
		AzureActiveDirectoryDeviceId:            convert.GraphToFrameworkString(data.GetAzureActiveDirectoryDeviceId()),
		AzureADDeviceId:                         convert.GraphToFrameworkString(data.GetAzureADDeviceId()),
		DeviceRegistrationState:                 convert.GraphToFrameworkEnum(data.GetDeviceRegistrationState()),
		DeviceCategoryDisplayName:               convert.GraphToFrameworkString(data.GetDeviceCategoryDisplayName()),
		IsSupervised:                            convert.GraphToFrameworkBool(data.GetIsSupervised()),
		ExchangeLastSuccessfulSyncDateTime:      convert.GraphToFrameworkTime(data.GetExchangeLastSuccessfulSyncDateTime()),
		ExchangeAccessState:                     convert.GraphToFrameworkEnum(data.GetExchangeAccessState()),
		ExchangeAccessStateReason:               convert.GraphToFrameworkEnum(data.GetExchangeAccessStateReason()),
		RemoteAssistanceSessionUrl:              convert.GraphToFrameworkString(data.GetRemoteAssistanceSessionUrl()),
		RemoteAssistanceSessionErrorDetails:     convert.GraphToFrameworkString(data.GetRemoteAssistanceSessionErrorDetails()),
		IsEncrypted:                             convert.GraphToFrameworkBool(data.GetIsEncrypted()),
		UserPrincipalName:                       convert.GraphToFrameworkString(data.GetUserPrincipalName()),
		Model:                                   convert.GraphToFrameworkString(data.GetModel()),
		Manufacturer:                            convert.GraphToFrameworkString(data.GetManufacturer()),
		IMEI:                                    convert.GraphToFrameworkString(data.GetImei()),
		ComplianceGracePeriodExpirationDateTime: convert.GraphToFrameworkTime(data.GetComplianceGracePeriodExpirationDateTime()),
		SerialNumber:                            convert.GraphToFrameworkString(data.GetSerialNumber()),
		PhoneNumber:                             convert.GraphToFrameworkString(data.GetPhoneNumber()),
		AndroidSecurityPatchLevel:               convert.GraphToFrameworkString(data.GetAndroidSecurityPatchLevel()),
		UserDisplayName:                         convert.GraphToFrameworkString(data.GetUserDisplayName()),
		WiFiMacAddress:                          convert.GraphToFrameworkString(data.GetWiFiMacAddress()),
		SubscriberCarrier:                       convert.GraphToFrameworkString(data.GetSubscriberCarrier()),
		MEID:                                    convert.GraphToFrameworkString(data.GetMeid()),
		TotalStorageSpaceInBytes:                convert.GraphToFrameworkInt64(data.GetTotalStorageSpaceInBytes()),
		FreeStorageSpaceInBytes:                 convert.GraphToFrameworkInt64(data.GetFreeStorageSpaceInBytes()),
		ManagedDeviceName:                       convert.GraphToFrameworkString(data.GetManagedDeviceName()),
		PartnerReportedThreatState:              convert.GraphToFrameworkEnum(data.GetPartnerReportedThreatState()),
		RetireAfterDateTime:                     convert.GraphToFrameworkTime(data.GetRetireAfterDateTime()),
		PreferMdmOverGroupPolicyAppliedDateTime: convert.GraphToFrameworkTime(data.GetPreferMdmOverGroupPolicyAppliedDateTime()),
		AutopilotEnrolled:                       convert.GraphToFrameworkBool(data.GetAutopilotEnrolled()),
		RequireUserEnrollmentApproval:           convert.GraphToFrameworkBool(data.GetRequireUserEnrollmentApproval()),
		ManagementCertificateExpirationDate:     convert.GraphToFrameworkTime(data.GetManagementCertificateExpirationDate()),
		ICCID:                                   convert.GraphToFrameworkString(data.GetIccid()),
		UDID:                                    convert.GraphToFrameworkString(data.GetUdid()),
		Notes:                                   convert.GraphToFrameworkString(data.GetNotes()),
		EthernetMacAddress:                      convert.GraphToFrameworkString(data.GetEthernetMacAddress()),
		PhysicalMemoryInBytes:                   convert.GraphToFrameworkInt64(data.GetPhysicalMemoryInBytes()),
		ProcessorArchitecture:                   convert.GraphToFrameworkEnum(data.GetProcessorArchitecture()),
		SpecificationVersion:                    convert.GraphToFrameworkString(data.GetSpecificationVersion()),
		JoinType:                                convert.GraphToFrameworkEnum(data.GetJoinType()),
		SkuFamily:                               convert.GraphToFrameworkString(data.GetSkuFamily()),
		SecurityPatchLevel:                      convert.GraphToFrameworkString(data.GetSecurityPatchLevel()),
		SkuNumber:                               convert.GraphToFrameworkInt32(data.GetSkuNumber()),
		ManagementFeatures:                      convert.GraphToFrameworkEnum(data.GetManagementFeatures()),
		EnrollmentProfileName:                   convert.GraphToFrameworkString(data.GetEnrollmentProfileName()),
		BootstrapTokenEscrowed:                  convert.GraphToFrameworkBool(data.GetBootstrapTokenEscrowed()),
		DeviceFirmwareConfigurationInterfaceManaged: convert.GraphToFrameworkBool(data.GetDeviceFirmwareConfigurationInterfaceManaged()),
		// TODO: Map complex/nested fields (HardwareInformation, DeviceActionResults, etc.)
	}
}
