package graphBetaAgentIdentityBlueprintCertificateCredential

import (
	"context"
	"fmt"
	"time"

	"github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/common/convert"
	"github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/common/crud"
	customrequests "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/common/custom_requests"
	errors "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/common/errors/kiota"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-log/tflog"
	graphmodels "github.com/microsoftgraph/msgraph-beta-sdk-go/models"
)

// Create handles the Create operation.
// Uses PATCH /applications/{id}/microsoft.graph.agentIdentityBlueprint to add a certificate
// to the keyCredentials property.
func (r *AgentIdentityBlueprintCertificateCredentialResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var object AgentIdentityBlueprintCertificateCredentialResourceModel

	tflog.Debug(ctx, fmt.Sprintf("Starting creation of resource: %s", ResourceName))

	resp.Diagnostics.Append(req.Plan.Get(ctx, &object)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := crud.HandleTimeout(ctx, object.Timeouts.Create, CreateTimeout*time.Second, &resp.Diagnostics)
	if cancel == nil {
		return
	}
	defer cancel()

	blueprintID := object.BlueprintID.ValueString()

	// First, get existing key credentials if we need to preserve them
	var existingCredentials []graphmodels.KeyCredentialable
	if !object.ReplaceExistingCertificates.ValueBool() {
		tflog.Debug(ctx, "Fetching existing key credentials to preserve them")

		existingApp, err := r.client.Applications().ByApplicationId(blueprintID).Get(ctx, nil)
		if err != nil {
			errors.HandleKiotaGraphError(ctx, err, resp, "Create (fetch existing)", r.ReadPermissions)
			return
		}

		if existingApp != nil {
			existingCredentials = existingApp.GetKeyCredentials()
			tflog.Debug(ctx, fmt.Sprintf("Found %d existing key credentials", len(existingCredentials)))
		}
	}

	// Construct the request body
	requestBody, err := constructResource(ctx, &object, existingCredentials)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error constructing certificate credential request",
			fmt.Sprintf("Could not construct request: %s", err.Error()),
		)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Patching application with certificate for blueprint_id: %s", blueprintID))

	// Use custom PATCH request with agentIdentityBlueprint cast endpoint
	config := customrequests.PatchRequestConfig{
		APIVersion:        customrequests.GraphAPIBeta,
		Endpoint:          "applications",
		ResourceID:        blueprintID,
		ResourceIDPattern: "/{id}",
		EndpointSuffix:    "/microsoft.graph.agentIdentityBlueprint",
		RequestBody:       requestBody,
	}

	err = customrequests.PatchRequestByResourceId(ctx, r.client.GetAdapter(), config)
	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, "Create", r.WritePermissions)
		return
	}

	// Wait for eventual consistency
	tflog.Debug(ctx, "Waiting 10 seconds for eventual consistency after create")
	time.Sleep(10 * time.Second)

	// Read the application to find the new keyId (it's generated by the API)
	updatedApp, err := r.client.
		Applications().
		ByApplicationId(blueprintID).
		Get(ctx, nil)

	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, "Create (fetch new keyId)", r.ReadPermissions)
		return
	}

	// Find the new credential by matching on displayName or other attributes
	// The new credential won't have a matching keyId since we didn't set one
	newCredentials := updatedApp.GetKeyCredentials()
	var newKeyID string
	for _, cred := range newCredentials {
		// Check if this credential matches our new one by display name
		if cred.GetDisplayName() != nil && *cred.GetDisplayName() == object.DisplayName.ValueString() {
			if cred.GetKeyId() != nil {
				newKeyID = cred.GetKeyId().String()
				object.KeyID = convert.GraphToFrameworkUUID(cred.GetKeyId())
				break
			}
		}
	}

	if newKeyID == "" {
		resp.Diagnostics.AddError(
			"Error finding new certificate credential",
			"Could not find the newly created certificate credential in the application",
		)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Found new certificate with key_id: %s", newKeyID))

	// Save initial state to allow read
	resp.Diagnostics.Append(resp.State.Set(ctx, &object)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read the resource to ensure state is fully populated
	readReq := resource.ReadRequest{State: resp.State, ProviderMeta: req.ProviderMeta}
	stateContainer := &crud.CreateResponseContainer{CreateResponse: resp}

	opts := crud.DefaultReadWithRetryOptions()
	opts.Operation = "Create"
	opts.ResourceTypeName = ResourceName

	err = crud.ReadWithRetry(ctx, r.Read, readReq, stateContainer, opts)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading resource state after create",
			fmt.Sprintf("Could not read resource state: %s: %s", ResourceName, err.Error()),
		)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished Create Method: %s", ResourceName))
}

// Read handles the Read operation.
// Uses GET /applications/{id} to retrieve the key credentials.
func (r *AgentIdentityBlueprintCertificateCredentialResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var object AgentIdentityBlueprintCertificateCredentialResourceModel

	tflog.Debug(ctx, fmt.Sprintf("Starting Read method for: %s", ResourceName))

	operation := "Read"
	if ctxOp := ctx.Value("retry_operation"); ctxOp != nil {
		if opStr, ok := ctxOp.(string); ok {
			operation = opStr
		}
	}

	resp.Diagnostics.Append(req.State.Get(ctx, &object)...)
	if resp.Diagnostics.HasError() {
		return
	}

	blueprintID := object.BlueprintID.ValueString()
	keyID := object.KeyID.ValueString()

	tflog.Debug(ctx, fmt.Sprintf("Reading %s with blueprint_id: %s and key_id: %s", ResourceName, blueprintID, keyID))

	ctx, cancel := crud.HandleTimeout(ctx, object.Timeouts.Read, ReadTimeout*time.Second, &resp.Diagnostics)
	if cancel == nil {
		return
	}
	defer cancel()

	// Fetch the application with keyCredentials
	application, err := r.client.Applications().ByApplicationId(blueprintID).Get(ctx, nil)
	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, operation, r.ReadPermissions)
		return
	}

	if application == nil {
		resp.Diagnostics.AddError(
			"Error reading certificate credential",
			fmt.Sprintf("Received nil application when reading blueprint_id: %s", blueprintID),
		)
		return
	}

	err = MapRemoteResourceStateToTerraform(ctx, &object, application, keyID)
	if err != nil {
		// If the certificate credential is not found, remove it from state
		if err.Error() == fmt.Sprintf("certificate credential with keyId %s not found in application", keyID) {
			tflog.Warn(ctx, fmt.Sprintf("Certificate credential with keyId %s not found in application %s, removing from state", keyID, blueprintID))
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError(
			"Error mapping remote state to Terraform state",
			fmt.Sprintf("Could not map remote resource state for %s: %s", ResourceName, err.Error()),
		)
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &object)...)
	if resp.Diagnostics.HasError() {
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished Read Method: %s", ResourceName))
}

// Update handles the Update operation.
// Certificate credentials cannot be updated in-place. This performs a delete and recreate.
func (r *AgentIdentityBlueprintCertificateCredentialResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan AgentIdentityBlueprintCertificateCredentialResourceModel
	var state AgentIdentityBlueprintCertificateCredentialResourceModel

	tflog.Debug(ctx, fmt.Sprintf("Starting Update method for: %s", ResourceName))

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := crud.HandleTimeout(ctx, state.Timeouts.Update, UpdateTimeout*time.Second, &resp.Diagnostics)
	if cancel == nil {
		return
	}
	defer cancel()

	blueprintID := state.BlueprintID.ValueString()
	oldKeyID := state.KeyID.ValueString()

	tflog.Debug(ctx, fmt.Sprintf("Updating certificate credential - removing old key_id: %s", oldKeyID))

	// Get existing credentials
	existingApp, err := r.client.Applications().ByApplicationId(blueprintID).Get(ctx, nil)
	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, "Update (fetch existing)", r.ReadPermissions)
		return
	}

	existingCredentials := existingApp.GetKeyCredentials()

	// Step 1: Remove the old credential
	deleteBody, err := constructDeleteResource(ctx, oldKeyID, existingCredentials)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error constructing delete request",
			fmt.Sprintf("Could not construct request: %s", err.Error()),
		)
		return
	}

	deleteConfig := customrequests.PatchRequestConfig{
		APIVersion:        customrequests.GraphAPIBeta,
		Endpoint:          "applications",
		ResourceID:        blueprintID,
		ResourceIDPattern: "/{id}",
		EndpointSuffix:    "/microsoft.graph.agentIdentityBlueprint",
		RequestBody:       deleteBody,
	}

	err = customrequests.PatchRequestByResourceId(ctx, r.client.GetAdapter(), deleteConfig)
	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, "Update (remove)", r.WritePermissions)
		return
	}

	tflog.Debug(ctx, "Successfully removed old certificate credential")

	// Wait for eventual consistency
	time.Sleep(5 * time.Second)

	// Refresh existing credentials after deletion
	existingApp, err = r.client.Applications().ByApplicationId(blueprintID).Get(ctx, nil)
	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, "Update (fetch after delete)", r.ReadPermissions)
		return
	}

	existingCredentials = existingApp.GetKeyCredentials()

	// Step 2: Add the new credential
	addBody, err := constructResource(ctx, &plan, existingCredentials)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error constructing add request",
			fmt.Sprintf("Could not construct request: %s", err.Error()),
		)
		return
	}

	addConfig := customrequests.PatchRequestConfig{
		APIVersion:        customrequests.GraphAPIBeta,
		Endpoint:          "applications",
		ResourceID:        blueprintID,
		ResourceIDPattern: "/{id}",
		EndpointSuffix:    "/microsoft.graph.agentIdentityBlueprint",
		RequestBody:       addBody,
	}

	err = customrequests.PatchRequestByResourceId(ctx, r.client.GetAdapter(), addConfig)
	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, "Update (add)", r.WritePermissions)
		return
	}

	tflog.Debug(ctx, "Successfully added new certificate credential")

	// Wait for eventual consistency
	time.Sleep(10 * time.Second)

	// Read the application to find the new keyId (it's generated by the API)
	updatedApp, err := r.client.
		Applications().
		ByApplicationId(blueprintID).
		Get(ctx, nil)

	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, "Update (fetch new keyId)", r.ReadPermissions)
		return
	}

	// Find the new credential by matching on displayName
	newCredentials := updatedApp.GetKeyCredentials()
	var newKeyID string
	for _, cred := range newCredentials {
		if cred.GetDisplayName() != nil && *cred.GetDisplayName() == plan.DisplayName.ValueString() {
			if cred.GetKeyId() != nil {
				newKeyID = cred.GetKeyId().String()
				plan.KeyID = convert.GraphToFrameworkUUID(cred.GetKeyId())
				break
			}
		}
	}

	if newKeyID == "" {
		resp.Diagnostics.AddError(
			"Error finding new certificate credential",
			"Could not find the newly created certificate credential in the application",
		)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Found new certificate with key_id: %s", newKeyID))

	// Save initial state to allow read
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Read the resource to ensure state is fully populated
	readReq := resource.ReadRequest{State: resp.State, ProviderMeta: req.ProviderMeta}
	stateContainer := &crud.UpdateResponseContainer{UpdateResponse: resp}

	opts := crud.DefaultReadWithRetryOptions()
	opts.Operation = "Update"
	opts.ResourceTypeName = ResourceName

	err = crud.ReadWithRetry(ctx, r.Read, readReq, stateContainer, opts)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error reading resource state after update",
			fmt.Sprintf("Could not read resource state: %s: %s", ResourceName, err.Error()),
		)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Finished Update Method: %s", ResourceName))
}

// Delete handles the Delete operation.
// Uses PATCH /applications/{id}/microsoft.graph.agentIdentityBlueprint to remove the certificate
// from the keyCredentials property while preserving other credentials.
func (r *AgentIdentityBlueprintCertificateCredentialResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data AgentIdentityBlueprintCertificateCredentialResourceModel

	tflog.Debug(ctx, fmt.Sprintf("Starting Delete method for: %s", ResourceName))

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := crud.HandleTimeout(ctx, data.Timeouts.Delete, DeleteTimeout*time.Second, &resp.Diagnostics)
	if cancel == nil {
		return
	}
	defer cancel()

	blueprintID := data.BlueprintID.ValueString()
	keyID := data.KeyID.ValueString()

	tflog.Debug(ctx, fmt.Sprintf("Deleting certificate credential with key_id: %s from blueprint: %s", keyID, blueprintID))

	// Get existing credentials
	existingApp, err := r.client.
		Applications().
		ByApplicationId(blueprintID).
		Get(ctx, nil)

	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, "Delete (fetch existing)", r.ReadPermissions)
		return
	}

	existingCredentials := existingApp.GetKeyCredentials()

	// Construct request body without the credential being deleted
	requestBody, err := constructDeleteResource(ctx, keyID, existingCredentials)
	if err != nil {
		resp.Diagnostics.AddError(
			"Error constructing delete request",
			fmt.Sprintf("Could not construct request: %s", err.Error()),
		)
		return
	}

	config := customrequests.PatchRequestConfig{
		APIVersion:        customrequests.GraphAPIBeta,
		Endpoint:          "applications",
		ResourceID:        blueprintID,
		ResourceIDPattern: "/{id}",
		EndpointSuffix:    "/microsoft.graph.agentIdentityBlueprint",
		RequestBody:       requestBody,
	}

	err = customrequests.PatchRequestByResourceId(ctx, r.client.GetAdapter(), config)

	if err != nil {
		errors.HandleKiotaGraphError(ctx, err, resp, "Delete", r.WritePermissions)
		return
	}

	tflog.Debug(ctx, fmt.Sprintf("Successfully deleted certificate credential with key_id: %s", keyID))
	tflog.Debug(ctx, fmt.Sprintf("Finished Delete Method: %s", ResourceName))
}
