package graphBetaChangeNotificationsSubscription

// subscriptionPermissionHints are Microsoft Graph permission names that may be required to create,
// read, renew, or delete a subscription, depending on the subscription **resource** path (Graph
// property **resource**), delegated vs. application context, and the exact path (some resource types use multiple
// paths with different permissions). Subscriptions use read (or read-equivalent) permissions only;
// Graph does not accept write-only permissions where read suffices.
//
// Source: https://learn.microsoft.com/en-us/graph/api/subscription-post-subscriptions?view=graph-rest-beta
var subscriptionPermissionHints = []string{
	"AiEnterpriseInteraction.Read",
	"AiEnterpriseInteraction.Read.All",
	"AiEnterpriseInteraction.Read.User",
	"ApprovalSolution.ReadWrite.All",
	"CallRecords.Read.All",
	"Channel.ReadBasic.All",
	"ChannelMember.Read.All",
	"ChannelMessage.Read.All",
	"ChannelMessage.Read.Group",
	"ChannelSettings.Read.All",
	"Chat.Manage.Chat",
	"Chat.Read",
	"Chat.Read.All",
	"Chat.ReadBasic",
	"Chat.ReadBasic.All",
	"Chat.ReadBasic.WhereInstalled",
	"Chat.Read.WhereInstalled",
	"Chat.ReadWrite",
	"Chat.ReadWrite.All",
	"Chat.ReadWrite.WhereInstalled",
	"ChatMember.Read.All",
	"ChatMember.Read.Chat",
	"ChatMember.Read.WhereInstalled",
	"ChatMember.ReadWrite.All",
	"ChatMember.ReadWrite.WhereInstalled",
	"ChatSettings.Read.Chat",
	"ChatSettings.ReadWrite.Chat",
	"Contacts.Read",
	"Calendars.Read",
	"Files.ReadWrite",
	"Files.ReadWrite.All",
	"Group.Read.All",
	"Group.ReadWrite.All",
	"HealthMonitoringAlertConfig.ReadWrite.All",
	"Mail.Read",
	"Mail.ReadBasic",
	"OnlineMeetingRecording.Read.All",
	"OnlineMeetingRecording.Read.Chat",
	"OnlineMeetingTranscript.Read.All",
	"OnlineMeetingTranscript.Read.Chat",
	"OnlineMeetings.Read.All",
	"OnlineMeetings.ReadWrite.All",
	"Presence.Read.All",
	"Printer.Read.All",
	"Printer.ReadWrite.All",
	"PrintTaskDefinition.ReadWrite.All",
	"Schedule.Read.All",
	"Schedule.ReadWrite.All",
	"SecurityEvents.ReadWrite.All",
	"Sites.ReadWrite.All",
	"Tasks.ReadWrite",
	"Tasks.ReadWrite.All",
	"Team.ReadBasic.All",
	"TeamMember.Read.All",
	"TeamMember.ReadWrite.All",
	"TeamSettings.Read.All",
	"User.Read.All",
	"VirtualEvent.Read",
	"VirtualEvent.Read.All",
}
