package graphBetaSettingsCatalog

import (
	sharedmodels "github.com/deploymenttheory/terraform-provider-microsoft365/internal/resources/common/shared_models/graph_beta"
	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// SettingsCatalogProfileResourceModel holds the configuration for a Settings Catalog profile.
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationpolicy?view=graph-rest-beta
type SettingsCatalogProfileResourceModel struct {
	ID                   types.String                                        `tfsdk:"id"`
	Name                 types.String                                        `tfsdk:"name"`
	Description          types.String                                        `tfsdk:"description"`
	Platforms            types.String                                        `tfsdk:"platforms"`
	Technologies         types.String                                        `tfsdk:"technologies"`
	SettingsCount        types.Int64                                         `tfsdk:"settings_count"`
	RoleScopeTagIds      []types.String                                      `tfsdk:"role_scope_tag_ids"`
	LastModifiedDateTime types.String                                        `tfsdk:"last_modified_date_time"`
	CreatedDateTime      types.String                                        `tfsdk:"created_date_time"`
	Settings             []DeviceManagementConfigurationSettingResourceModel `tfsdk:"settings"`
	IsAssigned           types.Bool                                          `tfsdk:"is_assigned"`
	//TemplateReference    *DeviceManagementConfigurationTemplateReferenceResourceModel `tfsdk:"template_reference"`
	Assignments *sharedmodels.SettingsCatalogSettingsAssignmentResourceModel `tfsdk:"assignments"`
	Timeouts    timeouts.Value                                               `tfsdk:"timeouts"`
}

// SettingResourceModel holds individual settings for the catalog configuration policy.
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsetting?view=graph-rest-beta
type DeviceManagementConfigurationSettingResourceModel struct {
	ODataType       types.String                                               `tfsdk:"odata_type"`
	SettingInstance *DeviceManagementConfigurationSettingInstanceResourceModel `tfsdk:"setting_instance"`
}

// DeviceManagementConfigurationSettingInstanceResourceModel  represents a setting instance within the catalog.
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-shared-devicemanagementconfigurationsettinginstance?view=graph-rest-beta
type DeviceManagementConfigurationSettingInstanceResourceModel struct {
	ODataType                   types.String                              `tfsdk:"odata_type"` // The OData type of the setting instance. Must be supplied within HCL
	SettingDefinitionID         types.String                              `tfsdk:"setting_definition_id"`
	ChoiceSettingValue          *ChoiceSettingValueResourceModel          `tfsdk:"choice"`
	ChoiceCollectionValue       *ChoiceCollectionValueResourceModel       `tfsdk:"choice_collection"`
	SimpleSettingValue          *SimpleSettingValueResourceModel          `tfsdk:"simple"`
	SimpleCollectionValue       *SimpleCollectionValueResourceModel       `tfsdk:"simple_collection"`
	GroupSettingValue           *GroupSettingValueResourceModel           `tfsdk:"group"`
	GroupSettingCollectionValue *GroupSettingCollectionValueResourceModel `tfsdk:"group_collection"`
	SettingGroupSettingValue    *SettingGroupSettingValueResourceModel    `tfsdk:"setting_group"`
	SettingGroupCollectionValue *SettingGroupCollectionValueResourceModel `tfsdk:"setting_group_collection"`
}

// DeviceManagementConfigurationChoiceSettingValueResourceModel represents the choice setting value.
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-deviceManagementConfigurationChoiceSettingValue?view=graph-rest-beta
type ChoiceSettingValueResourceModel struct {
	ODataType   types.String                                                `tfsdk:"odata_type"` // The OData type of the choice setting instance. Generated By SDK.
	IntValue    types.Int32                                                 `tfsdk:"integer_value"`
	StringValue types.String                                                `tfsdk:"string_value"`
	Children    []DeviceManagementConfigurationSettingInstanceResourceModel `tfsdk:"children"` // Children in docs are always of the same type as the parent. ChoiceSetting
}

// DeviceManagementConfigurationChoiceCollectionValueResourceModel represents the choice collection setting value.
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectiondefinition?view=graph-rest-beta
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationchoicesettingcollectioninstance?view=graph-rest-beta
type ChoiceCollectionValueResourceModel struct {
	ODataType   types.String                                                `tfsdk:"odata_type"` // The OData type of the choice collection setting instance. Generated By SDK.
	IntValue    []types.Int32                                               `tfsdk:"integer_value"`
	StringValue []types.String                                              `tfsdk:"string_value"`
	Children    []DeviceManagementConfigurationSettingInstanceResourceModel `tfsdk:"children"` // Children in docs are always of the same. ChoiceSetting.
}

// DeviceManagementConfigurationSimpleSettingValueResourceModel represents the simple setting value.
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-deviceManagementConfigurationSimpleSettingValue?view=graph-rest-beta
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationintegersettingvalue?view=graph-rest-beta
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationstringsettingvalue?view=graph-rest-beta
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsecretsettingvalue?view=graph-rest-beta
type SimpleSettingValueResourceModel struct {
	ODataType      types.String `tfsdk:"odata_type"` // The OData type of the simple setting instance. Generated By SDK.
	IntValue       types.Int32  `tfsdk:"integer_value"`
	StringValue    types.String `tfsdk:"string_value"`
	SecretValue    types.String `tfsdk:"secret_value"`
	State          types.String `tfsdk:"state"`
	ReferenceValue types.String `tfsdk:"reference_value"`
	Note           types.String `tfsdk:"note"`
}

// DeviceManagementConfigurationSimpleCollectionValueResourceModel represents the simple collection setting value.
// Reference: https://learn.microsoft.com/en-us/graph/api/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingcollectiondefinition-create?view=graph-rest-beta
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-devicemanagementconfigurationsimplesettingcollectioninstance?view=graph-rest-beta
type SimpleCollectionValueResourceModel struct {
	ODataType   types.String   `tfsdk:"odata_type"` // The OData type of the simple collection instance. Generated By SDK.
	IntValue    []types.Int32  `tfsdk:"integer_value"`
	StringValue []types.String `tfsdk:"string_value"`
	SecretValue []types.String `tfsdk:"secret_value"`
	State       []types.String `tfsdk:"state"`
	//Children    []DeviceManagementConfigurationSettingInstanceResourceModel `tfsdk:"children"` // docs says children are possible. but sdk doesn't support it ?
}

// GroupSettingValueResourceModel represents the group setting value.
// Reference:
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-deviceManagementConfigurationGroupSettingValue?view=graph-rest-beta
type GroupSettingValueResourceModel struct {
	ODataType types.String                                                `tfsdk:"odata_type"`
	Children  []DeviceManagementConfigurationSettingInstanceResourceModel `tfsdk:"children"` // Can contain children of any other instance type
}

// GroupCollectionValueResourceModel represents the group collection setting value.
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-deviceManagementConfigurationGroupSettingCollectionValue?view=graph-rest-beta
type GroupSettingCollectionValueResourceModel struct {
	ODataType types.String                                                `tfsdk:"odata_type"`
	Children  []DeviceManagementConfigurationSettingInstanceResourceModel `tfsdk:"children"` // Can contain children of any other instance type
}

// SettingsGroupSettingValueResourceModel represents the setting group instance.
// Appears to be unused presently
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-deviceManagementConfigurationSettingGroupInstance?view=graph-rest-beta
type SettingGroupSettingValueResourceModel struct {
	ODataType types.String `tfsdk:"odata_type"`
}

// SettingsGroupCollectionValueResourceModel represents the setting group collection instance.
// Appears to be unused presently
// Reference: https://learn.microsoft.com/en-us/graph/api/resources/intune-deviceconfigv2-deviceManagementConfigurationSettingGroupCollectionInstance?view=graph-rest-beta
type SettingGroupCollectionValueResourceModel struct {
	ODataType types.String `tfsdk:"odata_type"`
}
