package graphBetaSettingsCatalog

import (
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

// GetChoiceCollectionSchema returns the root schema for choice collection data type
// Change from returning SingleNestedAttribute to returning the Attributes map
func GetChoiceCollectionSchema(currentDepth int) map[string]schema.Attribute {
	if currentDepth >= MaxDepth {
		return map[string]schema.Attribute{}
	}

	return map[string]schema.Attribute{
		"odata_type": schema.StringAttribute{
			Computed:            true,
			MarkdownDescription: "The OData type of the choice collection setting instance. Generated by SDK.",
		},
		"string_value": schema.ListAttribute{
			Optional:            true,
			ElementType:         types.StringType,
			Description:         "Collection of string choice values",
			MarkdownDescription: "List of string values for choice collection setting.",
		},
		"integer_value": schema.ListAttribute{
			Optional:            true,
			ElementType:         types.Int32Type,
			Description:         "Collection of integer choice values",
			MarkdownDescription: "List of integer values for choice collection setting.",
		},
		"children": schema.SingleNestedAttribute{
			Optional:            true,
			Attributes:          GetChildrenAttributes(currentDepth + 1),
			Description:         "List of child setting configurations",
			MarkdownDescription: "List of child setting instances under the choice collection setting.",
		},
	}
}
