package handler

import (
	"fmt"
	"strings"
)

// buildFailureReport constructs the content for FAILURE_REPORT.md.
func buildFailureReport(date string, failedJobs []string, workflowURL, codecovURL string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("# Nightly Test Failure Report - %s\n\n", date))
	sb.WriteString("## Failed Jobs\n\n")

	for _, job := range failedJobs {
		sb.WriteString(fmt.Sprintf("### ❌ %s\n", job))

		if job == "Provider-Core" {
			sb.WriteString("- **Package:** internal/client, internal/provider, internal/helpers, internal/utilities\n")
		} else {
			sb.WriteString(fmt.Sprintf("One or more %s tests failed. Check the workflow run for details.\n", strings.ToLower(job)))
		}

		sb.WriteString("\n")
	}

	sb.WriteString("## Links\n")
	sb.WriteString(fmt.Sprintf("- [Workflow Run](%s)\n", workflowURL))
	sb.WriteString(fmt.Sprintf("- [Codecov Report](%s)\n\n", codecovURL))

	sb.WriteString("## Action Required\n")
	sb.WriteString("Please investigate the failed tests and fix the issues. ")
	sb.WriteString("Once fixed, delete this report file and close the PR and associated issue.\n")

	return sb.String()
}

// buildCommitMessage constructs the git commit message.
func buildCommitMessage(date, failedJobs, workflowURL string) string {
	var sb strings.Builder

	sb.WriteString(fmt.Sprintf("chore: nightly test failure report - %s\n\n", date))
	sb.WriteString(fmt.Sprintf("Failed jobs: %s\n\n", failedJobs))
	sb.WriteString("See FAILURE_REPORT.md for details.\n\n")
	sb.WriteString(fmt.Sprintf("Generated by workflow run: %s", workflowURL))

	return sb.String()
}

// buildPRTitle constructs the pull request title.
func buildPRTitle(failedJobs, date string) string {
	return fmt.Sprintf("Fix: Nightly Tests Failed - %s - %s", failedJobs, date)
}

// buildPRBody constructs the pull request body.
func buildPRBody(date, failedJobs, workflowURL, codecovURL string) string {
	var sb strings.Builder

	sb.WriteString("## Nightly Test Failures Detected\n\n")
	sb.WriteString("This PR documents nightly test failures that require investigation.\n\n")
	sb.WriteString(fmt.Sprintf("**Date:** %s\n", date))
	sb.WriteString(fmt.Sprintf("**Failed Jobs:** %s\n\n", failedJobs))
	sb.WriteString("See `FAILURE_REPORT.md` for detailed information.\n\n")
	sb.WriteString(fmt.Sprintf("**Workflow Run:** %s\n", workflowURL))
	sb.WriteString(fmt.Sprintf("**Codecov:** %s\n\n", codecovURL))

	sb.WriteString("### Next Steps\n")
	sb.WriteString("1. Review the failure report and workflow run logs\n")
	sb.WriteString("2. Fix the failing tests\n")
	sb.WriteString("3. Verify fixes pass locally\n")
	sb.WriteString("4. Push fixes to main branch\n")
	sb.WriteString("5. Close this PR and delete the branch\n")
	sb.WriteString("6. Close the associated issue\n")

	return sb.String()
}

// buildIssueTitle constructs the issue title.
func buildIssueTitle(date, failedJobs string) string {
	return fmt.Sprintf("Nightly Tests Failed - %s - %s", date, failedJobs)
}

// buildIssueBody constructs the issue body.
func buildIssueBody(date, failedJobs, workflowURL, prURL, codecovURL string) string {
	var sb strings.Builder

	sb.WriteString("## Nightly Tests Failed\n\n")
	sb.WriteString(fmt.Sprintf("**Date:** %s\n", date))
	sb.WriteString(fmt.Sprintf("**Failed Jobs:** %s\n\n", failedJobs))

	sb.WriteString("### Links\n")
	sb.WriteString(fmt.Sprintf("- **Workflow Run:** %s\n", workflowURL))
	sb.WriteString(fmt.Sprintf("- **Tracking PR:** %s\n", prURL))
	sb.WriteString(fmt.Sprintf("- **Codecov Report:** %s\n\n", codecovURL))

	sb.WriteString("### Action Required\n")
	sb.WriteString("Please investigate the failures and implement fixes. ")
	sb.WriteString("See the tracking PR for detailed information.\n")

	return sb.String()
}
