package graphBetaApplication

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
)

// applicationConsistencyPredicate returns a consistency predicate for ReadWithRetry that verifies
// the application resource write has propagated across Microsoft Entra replicas before accepting
// the read as authoritative.
//
// The predicate compares all user-specified mutable fields from the expected plan against the
// state returned by the read. A stale replica returns the pre-write version of the object,
// causing at least one field to differ and triggering a retry.
//
// Computed-only fields (app_id, created_date_time, deleted_date_time, disabled_by_microsoft_status,
// publisher_domain) are not compared — they are set by the API and are not meaningful signals
// for write propagation. Optional+Computed object fields are only compared when explicitly set
// in the plan, to avoid false failures caused by API-supplied defaults.
//
// See: https://devblogs.microsoft.com/identity/designing-for-eventual-consistency-for-microsoft-entra/
func applicationConsistencyPredicate(expected *ApplicationResourceModel) func(ctx context.Context, state tfsdk.State) bool {
	return func(ctx context.Context, state tfsdk.State) bool {
		var actual ApplicationResourceModel
		if diags := state.Get(ctx, &actual); diags.HasError() {
			return false
		}

		if actual.Id.IsNull() || actual.Id.IsUnknown() || actual.Id.ValueString() == "" {
			return false
		}

		// app_id is Computed — the client ID generated by Entra, never set from plan.
		// Its presence confirms the replica has the full object.
		if actual.AppId.IsNull() || actual.AppId.IsUnknown() || actual.AppId.ValueString() == "" {
			return false
		}

		// Compare all user-specified mutable fields. If any field set in the plan does not
		// match the read-back state, the responding replica has not yet received the write.
		if !actual.DisplayName.Equal(expected.DisplayName) {
			return false
		}
		if !expected.Description.IsNull() && !expected.Description.IsUnknown() {
			if !actual.Description.Equal(expected.Description) {
				return false
			}
		}
		if !expected.SignInAudience.IsNull() && !expected.SignInAudience.IsUnknown() {
			if !actual.SignInAudience.Equal(expected.SignInAudience) {
				return false
			}
		}
		if !expected.Notes.IsNull() && !expected.Notes.IsUnknown() {
			if !actual.Notes.Equal(expected.Notes) {
				return false
			}
		}
		if !expected.IsDeviceOnlyAuthSupported.IsNull() && !expected.IsDeviceOnlyAuthSupported.IsUnknown() {
			if !actual.IsDeviceOnlyAuthSupported.Equal(expected.IsDeviceOnlyAuthSupported) {
				return false
			}
		}
		if !expected.IsFallbackPublicClient.IsNull() && !expected.IsFallbackPublicClient.IsUnknown() {
			if !actual.IsFallbackPublicClient.Equal(expected.IsFallbackPublicClient) {
				return false
			}
		}
		if !expected.ServiceManagementReference.IsNull() && !expected.ServiceManagementReference.IsUnknown() {
			if !actual.ServiceManagementReference.Equal(expected.ServiceManagementReference) {
				return false
			}
		}
		if !expected.Tags.IsNull() && !expected.Tags.IsUnknown() {
			if !actual.Tags.Equal(expected.Tags) {
				return false
			}
		}
		if !expected.GroupMembershipClaims.IsNull() && !expected.GroupMembershipClaims.IsUnknown() {
			if !actual.GroupMembershipClaims.Equal(expected.GroupMembershipClaims) {
				return false
			}
		}
		if !expected.OwnerUserIds.IsNull() && !expected.OwnerUserIds.IsUnknown() {
			if !actual.OwnerUserIds.Equal(expected.OwnerUserIds) {
				return false
			}
		}
		// Optional+Computed object fields: only compare if explicitly set in the plan.
		if !expected.Api.IsNull() && !expected.Api.IsUnknown() {
			if !actual.Api.Equal(expected.Api) {
				return false
			}
		}
		if !expected.AppRoles.IsNull() && !expected.AppRoles.IsUnknown() {
			if !actual.AppRoles.Equal(expected.AppRoles) {
				return false
			}
		}
		if !expected.Info.IsNull() && !expected.Info.IsUnknown() {
			if !actual.Info.Equal(expected.Info) {
				return false
			}
		}
		if !expected.OptionalClaims.IsNull() && !expected.OptionalClaims.IsUnknown() {
			if !actual.OptionalClaims.Equal(expected.OptionalClaims) {
				return false
			}
		}
		if !expected.ParentalControlSettings.IsNull() && !expected.ParentalControlSettings.IsUnknown() {
			if !actual.ParentalControlSettings.Equal(expected.ParentalControlSettings) {
				return false
			}
		}
		if !expected.PublicClient.IsNull() && !expected.PublicClient.IsUnknown() {
			if !actual.PublicClient.Equal(expected.PublicClient) {
				return false
			}
		}
		if !expected.RequiredResourceAccess.IsNull() && !expected.RequiredResourceAccess.IsUnknown() {
			if !actual.RequiredResourceAccess.Equal(expected.RequiredResourceAccess) {
				return false
			}
		}
		if !expected.Spa.IsNull() && !expected.Spa.IsUnknown() {
			if !actual.Spa.Equal(expected.Spa) {
				return false
			}
		}
		if !expected.Web.IsNull() && !expected.Web.IsUnknown() {
			if !actual.Web.Equal(expected.Web) {
				return false
			}
		}
		if !expected.SignInAudienceRestrictions.IsNull() && !expected.SignInAudienceRestrictions.IsUnknown() {
			if !actual.SignInAudienceRestrictions.Equal(expected.SignInAudienceRestrictions) {
				return false
			}
		}

		return true
	}
}
