package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/action"

	// Graph Beta - Device management actions
	graphBetaDeviceManagementManagedDeviceActivateDeviceEsim "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/activate_device_esim"
	graphBetaDeviceManagementManagedDeviceBypassActivationLock "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/bypass_activation_lock"
	graphBetaDeviceManagementManagedDeviceCleanWindowsDevice "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/clean_windows_device"
	graphBetaDeviceManagementManagedDeviceCreateDeviceLogCollectionRequest "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/create_device_log_collection_request"
	graphBetaDeviceManagementManagedDeviceDeleteUserFromSharedAppleDevice "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/delete_user_from_shared_apple_device"
	graphBetaDeviceManagementManagedDeviceDeprovision "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/deprovision"
	graphBetaDeviceManagementManagedDeviceDisable "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/disable"
	graphBetaDeviceManagementManagedDeviceDisableLostMode "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/disable_lost_mode"
	graphBetaDeviceManagementManagedDeviceEnableLostMode "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/enable_lost_mode"
	graphBetaDeviceManagementManagedDeviceGetFileVaultKey "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/get_file_vault_key"
	graphBetaDeviceManagementManagedDeviceInitiateDeviceAttestation "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/initiate_device_attestation"
	graphBetaDeviceManagementManagedDeviceInitiateMobileDeviceManagementKeyRecovery "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/initiate_mobile_device_management_key_recovery"
	graphBetaDeviceManagementManagedDeviceInitiateOnDemandProactiveRemediation "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/initiate_on_demand_proactive_remediation"
	graphBetaDeviceManagementManagedDeviceLocateDevice "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/locate_device"
	graphBetaDeviceManagementManagedDeviceLogoutSharedAppleDeviceActiveUser "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/logout_shared_apple_device_active_user"
	graphBetaDeviceManagementManagedDeviceMoveDevicesToOU "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/move_devices_to_ou"
	graphBetaDeviceManagementManagedDevicePauseConfigurationRefresh "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/pause_configuration_refresh"
	graphBetaDeviceManagementManagedDevicePlayLostModeSound "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/play_lost_mode_sound"
	graphBetaDeviceManagementManagedDeviceRebootNow "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/reboot_now"
	graphBetaDeviceManagementManagedDeviceRecoverPasscode "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/recover_passcode"
	graphBetaDeviceManagementManagedDeviceReenable "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/reenable"
	graphBetaDeviceManagementManagedDeviceRemoteLock "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/remote_lock"
	graphBetaDeviceManagementManagedDeviceRemoteDeviceFirmwareConfigurationInterfaceManagement "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/remove_device_firmware_configuration_interface_management"
	graphBetaDeviceManagementManagedDeviceResetPasscode "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/reset_passcode"
	graphBetaDeviceManagementManagedDeviceRetire "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/retire"
	graphBetaDeviceManagementManagedDeviceRevokeAppleVppLicenses "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/revoke_apple_vpp_licenses"
	graphBetaDeviceManagementManagedDeviceRotateBitLockerKeys "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/rotate_bitlocker_keys"
	graphBetaDeviceManagementManagedDeviceRotateFileVaultKey "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/rotate_file_vault_key"
	graphBetaDeviceManagementManagedDeviceRotateLocalAdminPassword "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/rotate_local_admin_password"
	graphBetaDeviceManagementManagedDeviceSendCustomNotificationToCompanyPortal "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/send_custom_notification_to_company_portal"
	graphBetaDeviceManagementManagedDeviceSetDeviceName "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/set_device_name"
	graphBetaDeviceManagementManagedDeviceShutdown "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/shutdown"
	graphBetaDeviceManagementManagedDeviceSyncDevice "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/sync_device"
	graphBetaDeviceManagementManagedDeviceTriggerConfigurationManagerAction "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/trigger_configuration_manager_action"
	graphBetaDeviceManagementManagedDeviceUpdateWindowsDeviceAccount "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/update_windows_device_account"
	graphBetaDeviceManagementManagedDeviceWindowsDefenderScan "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/windows_defender_scan"
	graphBetaDeviceManagementManagedDeviceWindowsDefenderUpdateSignatures "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/windows_defender_update_signatures"
	graphBetaDeviceManagementManagedDeviceWipe "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/managed_device/wipe"
	graphBetaDeviceManagementWindows365ApplyCloudPcProvisioningPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/windows_365/apply_cloud_pc_provisioning_policy"
	graphBetaDeviceManagementWindowsAutopilotDeviceIdentityAllowNextEnrollment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/windows_autopilot_device_identity/allow_next_enrollment"
	graphBetaDeviceManagementWindowsAutopilotDeviceIdentityAssignUserToDevice "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/windows_autopilot_device_identity/assign_user_to_device"
	graphBetaDeviceManagementWindowsAutopilotDeviceIdentityUnassignUserFromDevice "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/windows_autopilot_device_identity/unassign_user_from_device"
	graphBetaDeviceManagementWindowsAutopilotDeviceIdentityUpdateDeviceProperties "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/actions/device_management/graph_beta/windows_autopilot_device_identity/update_device_properties"
)

// Actions returns a slice of functions that each return an action.Action.
// This function is a method of the M365Provider type and takes a context.Context as an argument.
// The returned slice is intended to hold the Microsoft 365 provider actions.
//
// Parameters:
//   - ctx: The context for controlling cancellation and timeout.
//
// Returns:
//
//	[]func() action.Action: A slice of functions, each returning an action.Action.
//
// Actions returns a slice of functions that each return an action.Action.
func (p *M365Provider) Actions(ctx context.Context) []func() action.Action {
	return []func() action.Action{
		// Graph Beta - Device management actions
		graphBetaDeviceManagementManagedDeviceActivateDeviceEsim.NewActivateDeviceEsimManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceBypassActivationLock.NewBypassActivationLockManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceCleanWindowsDevice.NewCleanWindowsManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceCreateDeviceLogCollectionRequest.NewCreateDeviceLogCollectionRequestManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceDeleteUserFromSharedAppleDevice.NewDeleteUserFromSharedAppleDeviceAction,
		graphBetaDeviceManagementManagedDeviceDeprovision.NewDeprovisionManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceDisable.NewDisableManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceDisableLostMode.NewDisableLostModeManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceEnableLostMode.NewEnableLostModeManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceGetFileVaultKey.NewGetFileVaultKeyManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceInitiateDeviceAttestation.NewInitiateDeviceAttestationManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceInitiateMobileDeviceManagementKeyRecovery.NewInitiateMobileDeviceManagementKeyRecoveryManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceInitiateOnDemandProactiveRemediation.NewInitiateOnDemandProactiveRemediationManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceLocateDevice.NewLocateManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceMoveDevicesToOU.NewMoveDevicesToOUManagedDeviceAction,
		graphBetaDeviceManagementManagedDevicePauseConfigurationRefresh.NewPauseConfigurationRefreshManagedDeviceAction,
		graphBetaDeviceManagementManagedDevicePlayLostModeSound.NewPlayLostModeSoundManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceLogoutSharedAppleDeviceActiveUser.NewLogoutSharedAppleDeviceActiveUserAction,
		graphBetaDeviceManagementManagedDeviceRebootNow.NewRebootNowManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceRecoverPasscode.NewRecoverManagedDevicePasscodeAction,
		graphBetaDeviceManagementManagedDeviceReenable.NewReenableManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceRemoteDeviceFirmwareConfigurationInterfaceManagement.NewRemoveDeviceFirmwareConfigurationInterfaceManagementManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceRemoteLock.NewRemoteLockManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceResetPasscode.NewResetManagedDevicePasscodeAction,
		graphBetaDeviceManagementManagedDeviceRetire.NewRetireManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceSetDeviceName.NewSetDeviceNameManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceRevokeAppleVppLicenses.NewRevokeAppleVppLicensesAction,
		graphBetaDeviceManagementManagedDeviceRotateBitLockerKeys.NewRotateBitLockerKeysAction,
		graphBetaDeviceManagementManagedDeviceRotateFileVaultKey.NewRotateFileVaultKeyManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceRotateLocalAdminPassword.NewRotateLocalAdminPasswordManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceSendCustomNotificationToCompanyPortal.NewSendCustomNotificationToCompanyPortalAction,
		graphBetaDeviceManagementManagedDeviceShutdown.NewShutdownManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceSyncDevice.NewSyncManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceTriggerConfigurationManagerAction.NewTriggerConfigurationManagerActionManagedDeviceAction,
		graphBetaDeviceManagementManagedDeviceUpdateWindowsDeviceAccount.NewUpdateWindowsDeviceAccountAction,
		graphBetaDeviceManagementManagedDeviceWindowsDefenderScan.NewWindowsDefenderScanAction,
		graphBetaDeviceManagementManagedDeviceWindowsDefenderUpdateSignatures.NewWindowsDefenderUpdateSignaturesAction,
		graphBetaDeviceManagementManagedDeviceWipe.NewWipeManagedDeviceAction,
		graphBetaDeviceManagementWindowsAutopilotDeviceIdentityAllowNextEnrollment.NewAllowNextEnrollmentAction,
		graphBetaDeviceManagementWindowsAutopilotDeviceIdentityAssignUserToDevice.NewAssignUserToDeviceAction,
		graphBetaDeviceManagementWindowsAutopilotDeviceIdentityUnassignUserFromDevice.NewUnassignUserFromDeviceAction,
		graphBetaDeviceManagementWindowsAutopilotDeviceIdentityUpdateDeviceProperties.NewUpdateDevicePropertiesAction,
		graphBetaDeviceManagementWindows365ApplyCloudPcProvisioningPolicy.NewApplyCloudPcProvisioningPolicyAction,

		// Add microsoft 365 provider actions here
	}
}
