package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"

	// Graph Beta - Applications datasources
	graphBetaApplicationsServicePrincipal "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/applications/graph_beta/service_principal"

	// Graph Beta - Intune datasources
	graphBetaDeviceAndAppManagementApplicationCategory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_and_app_management/graph_beta/application_category"
	graphBetaDeviceAndAppManagementMobileApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_and_app_management/graph_beta/mobile_app"
	graphBetaDeviceAndAppManagementMobileAppCatalogPackage "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_and_app_management/graph_beta/mobile_app_catalog_package"
	graphBetaDeviceAndAppManagementMobileAppRelationship "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_and_app_management/graph_beta/mobile_app_relationship"
	graphBetaDeviceManagementAssignmentFilter "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/assignment_filter"
	graphBetaDeviceManagementDeviceCategory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/device_category"
	graphBetaDeviceManagementGroupPolicyCategories "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/group_policy_categories"
	graphBetaDeviceManagementGroupPolicyValueReference "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/group_policy_value_reference"
	graphBetaDeviceManagementLinuxPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/linux_platform_script"
	graphBetaDeviceManagementManagedDevice "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/managed_device"
	graphBetaDeviceManagementReuseablePolicySettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/reuseable_policy_settings"
	graphBetaDeviceManagementRoleScopeTag "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/role_scope_tag"
	graphBetaDeviceManagementWindowsDriverUpdateInventory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/windows_driver_update_inventory"
	graphBetaDeviceManagementWindowsDriverUpdateProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/windows_driver_update_profile"
	graphBetaDeviceManagementWindowsFeatureUpdateProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/windows_feature_update_policy"
	graphBetaDeviceManagementWindowsPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/windows_platform_script"
	graphBetaDeviceManagementWindowsQualityUpdateExpeditePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/windows_quality_update_expedite_policy"
	graphBetaDeviceManagementWindowsQualityUpdatePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/windows_quality_update_policy"
	graphBetaDeviceManagementWindowsRemediationScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/windows_remediation_script"
	graphBetaDeviceManagementWindowsUpdateCatalogItem "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/windows_update_catalog_item"
	graphBetaDeviceManagementWindowsUpdateRing "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/device_management/graph_beta/windows_update_ring"

	// Graph Beta - Directory Management datasources
	graphBetaIdentityAndAccessDirectorySettingTemplates "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/identity_and_access/graph_beta/directory_setting_templates"

	// Graph Beta - Groups datasources
	graphBetaGroupsGroup "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/groups/graph_beta/group"

	// Graph Beta - Identity and Access datasources
	graphBetaIdentityAndAccessConditionalAccessTemplate "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/identity_and_access/graph_beta/conditional_access_template"
	graphBetaIdentityAndAccessRoleDefinitions "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/identity_and_access/graph_beta/role_definitions"
	graphBetaIdentityAndAccessTenantInformation "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/identity_and_access/graph_beta/tenant_information"

	// Graph Beta - M365 Admin datasources
	graphBetaM365AdminBrowserSite "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/m365_admin/graph_beta/browser_site"
	graphBetaM365AdminBrowserSiteList "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/m365_admin/graph_beta/browser_site_list"

	// Graph Beta - Multitenant Management datasources
	graphBetaMultitenantManagementAggregatedPolicyCompliances "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/multitenant_management/graph_beta/aggregated_policy_compliances"
	graphBetaMultitenantManagementAuditEvents "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/multitenant_management/graph_beta/audit_events"

	// Graph v1.0 - Directory Management datasources
	graphBetaIdentityAndAccessSubscribedSkus "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/identity_and_access/graph_v1.0/subscribed_skus"

	// Graph Beta - Windows 365 datasources
	graphBetaWindows365CloudPcAuditEvent "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/windows_365/graph_beta/cloud_pc_audit_event"
	graphBetaWindows365CloudPcDeviceImage "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/windows_365/graph_beta/cloud_pc_device_image"
	graphBetaWindows365CloudPcFrontlineServicePlan "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/windows_365/graph_beta/cloud_pc_frontline_service_plan"
	graphBetaWindows365CloudPcGalleryImage "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/windows_365/graph_beta/cloud_pc_gallery_image"
	graphBetaWindows365CloudPcSourceDeviceImage "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/windows_365/graph_beta/cloud_pc_source_device_image"
	graphBetaWindows365CloudPcs "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/windows_365/graph_beta/cloud_pcs"

	// Utilities
	utilityDeploymentScheduler "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/deployment_scheduler"
	utilityEntraIdSidConverter "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/entra_id_sid_converter"
	utilityGuidListSharder "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/guid_list_sharder"
	utilityItunesAppMetadata "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/itunes_app_metadata"
	utilityLicensingServicePlanReference "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/licensing_service_plan_reference"
	utilityMacOSPKGAppMetadata "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/macos_pkg_app_metadata"
	utilityMicrosoft365EndpointReference "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/microsoft_365_endpoint_reference"
	utilityMicrosoftStorePackageManifestMetadata "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/microsoft_store_package_manifest_metadata"
	utilityWindowsMSIAppMetadata "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/windows_msi_app_metadata"
	utilityWindowsRemediationScriptRegistryKeyGenerator "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/datasources/utility/windows_remediation_script_registry_key_generator"
)

// DataSources returns a slice of functions that each return a datasource.DataSource.
// This function is a method of the M365Provider type and takes a context.Context as an argument.
// The returned slice is intended to hold the Microsoft 365 provider datasources.
//
// Parameters:
//   - ctx: The context for controlling cancellation and timeout.
//
// Returns:
//
//	[]func() datasource.DataSource: A slice of functions, each returning a datasource.DataSource.
func (p *M365Provider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		// Graph Beta - Applications
		graphBetaApplicationsServicePrincipal.NewServicePrincipalDataSource,

		// Graph Beta - Device and app management
		graphBetaDeviceAndAppManagementApplicationCategory.NewApplicationCategoryDataSource,
		graphBetaDeviceAndAppManagementMobileApp.NewMobileAppDataSource,
		graphBetaDeviceAndAppManagementMobileAppCatalogPackage.NewMobileAppCatalogPackageDataSource,
		graphBetaDeviceAndAppManagementMobileAppRelationship.NewMobileAppRelationshipDataSource,

		// Graph Beta - Device management
		graphBetaDeviceManagementAssignmentFilter.NewAssignmentFilterDataSource,
		graphBetaDeviceManagementDeviceCategory.NewDeviceCategoryDataSource,
		graphBetaDeviceManagementGroupPolicyCategories.NewGroupPolicyCategoryDataSource,
		graphBetaDeviceManagementGroupPolicyValueReference.NewGroupPolicyValueReferenceDataSource,
		graphBetaDeviceManagementLinuxPlatformScript.NewLinuxPlatformScriptDataSource,
		graphBetaDeviceManagementManagedDevice.NewManagedDeviceDataSource,
		graphBetaDeviceManagementReuseablePolicySettings.NewReuseablePolicySettingsDataSource,
		graphBetaDeviceManagementRoleScopeTag.NewRoleScopeTagDataSource,
		graphBetaDeviceManagementWindowsDriverUpdateProfile.NewWindowsDriverUpdateProfileDataSource,
		graphBetaDeviceManagementWindowsDriverUpdateInventory.NewWindowsDriverUpdateInventoryDataSource,
		graphBetaDeviceManagementWindowsFeatureUpdateProfile.NewWindowsFeatureUpdateProfileDataSource,
		graphBetaDeviceManagementWindowsQualityUpdatePolicy.NewWindowsQualityUpdateProfileDataSource,
		graphBetaDeviceManagementWindowsPlatformScript.NewWindowsPlatformScriptDataSource,
		graphBetaDeviceManagementWindowsRemediationScript.NewWindowsRemediationScriptDataSource,
		graphBetaDeviceManagementWindowsUpdateCatalogItem.NewWindowsUpdateCatalogItemDataSource,
		graphBetaDeviceManagementWindowsQualityUpdateExpeditePolicy.NewWindowsQualityUpdateExpeditePolicyDataSource,
		graphBetaDeviceManagementWindowsUpdateRing.NewWindowsUpdateRingDataSource,

		// Graph Beta - Groups datasources
		graphBetaGroupsGroup.NewGroupDataSource,

		// Graph Beta - Identity and Access datasources
		graphBetaIdentityAndAccessConditionalAccessTemplate.NewConditionalAccessTemplateDataSource,
		graphBetaIdentityAndAccessDirectorySettingTemplates.NewDirectorySettingTemplatesDataSource,
		graphBetaIdentityAndAccessRoleDefinitions.NewRoleDefinitionsDataSource,
		graphBetaIdentityAndAccessTenantInformation.NewTenantInformationDataSource,
		// Graph Beta - M365 Admin datasources
		graphBetaM365AdminBrowserSite.NewBrowserSiteDataSource,
		graphBetaM365AdminBrowserSiteList.NewBrowserSiteListDataSource,
		// Graph Beta - Multitenant Management datasources
		graphBetaMultitenantManagementAggregatedPolicyCompliances.NewAggregatedPolicyCompliancesDataSource,
		graphBetaMultitenantManagementAuditEvents.NewAuditEventsDataSource,
		// Graph Beta - Windows 365 datasources
		graphBetaWindows365CloudPcAuditEvent.NewCloudPcAuditEventDataSource,
		graphBetaWindows365CloudPcFrontlineServicePlan.NewCloudPcFrontlineServicePlanDataSource,
		graphBetaWindows365CloudPcGalleryImage.NewCloudPcGalleryImageDataSource,
		graphBetaWindows365CloudPcDeviceImage.NewCloudPcDeviceImageDataSource,
		graphBetaWindows365CloudPcs.NewCloudPcsDataSource,
		graphBetaWindows365CloudPcSourceDeviceImage.NewCloudPcSourceDeviceImageDataSource,

		// Graph v1.0 - Identity and Access datasources
		graphBetaIdentityAndAccessSubscribedSkus.NewSubscribedSkusDataSource,

		// Utilities
		utilityDeploymentScheduler.NewDeploymentSchedulerDataSource,
		utilityEntraIdSidConverter.NewEntraIdSidConverterDataSource,
		utilityGuidListSharder.NewGuidListSharderDataSource,
		utilityWindowsRemediationScriptRegistryKeyGenerator.NewWindowsRemediationScriptRegistryKeyGeneratorDataSource,
		utilityMacOSPKGAppMetadata.NewMacOSPKGAppMetadataDataSource,
		utilityItunesAppMetadata.NewItunesAppMetadataDataSource,
		utilityLicensingServicePlanReference.NewlicensingServicePlanReferenceDataSource,
		utilityMicrosoft365EndpointReference.NewMicrosoft365EndpointReferenceDataSource,
		utilityMicrosoftStorePackageManifestMetadata.NewMicrosoftStorePackageManifestDataSource,
		utilityWindowsMSIAppMetadata.NewWindowsMSIAppMetadataDataSource,

		// Add microsoft 365 provider datasources here
	}
}
