package provider

import (
	"context"
	// Graph Beta - Device & app management
	graphBetaDeviceAndAppManagementApplicationCategory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/application_category"
	graphBetaDeviceAndAppManagementMacOSDmgApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_dmg_app"
	graphBetaDeviceAndAppManagementMacOSLobApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_lob_app"
	graphBetaDeviceAndAppManagementMacOSPKGApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_pkg_app"
	graphBetaDeviceAndAppManagementAppAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/mobile_app_assignment"
	graphBetaDeviceAndAppManagementWinGetApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/winget_app"

	// Graph Beta - Device management
	graphBetaDeviceManagementAppleUserInitiatedEnrollmentProfileAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/apple_user_initiated_enrollment_profile_assignment"
	graphBetaDeviceManagementAssignmentFilter "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/assignment_filter"
	graphBetaDeviceManagementDeviceCategory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_category"
	graphBetaDeviceManagementDeviceEnrollmentLimitConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_enrollment_limit_configuration"
	graphBetaDeviceManagementDeviceEnrollmentNotificationConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_enrollment_notification_configuration"
	graphBetaDeviceManagementEndpointPrivilegeManagement "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/endpoint_privilege_management"
	graphBetaDeviceManagementLinuxPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/linux_platform_script"
	graphBetaDeviceManagementMacOSPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_platform_script"
	graphBetaDeviceManagementMacOSSoftwareUpdateConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_software_update_configuration"
	graphBetaDeviceManagementManagedDeviceCleanupRule "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/managed_device_cleanup_rule"
	graphBetaDeviceManagementOperationApprovalPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/operation_approval_policy"
	graphBetaDeviceManagementRBACResourceOperation "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/rbac_resource_operation"
	graphBetaDeviceManagementReuseablePolicySettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/reuseable_policy_settings"
	graphBetaDeviceManagementRoleAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/role_assignment"
	graphBetaDeviceManagementRoleDefinition "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/role_definition"
	graphBetaDeviceManagementRoleScopeTag "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/role_scope_tag"
	graphBetaDeviceManagementSettingsCatalog "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog"
	graphBetaDeviceManagementConfigurationPolicyAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_assignment"
	graphBetaDeviceManagementSettingsCatalogJson "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_json"
	graphBetaDeviceManagementSettingsCatalogTemplateJson "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_template_json"
	graphBetaDeviceManagementTermsAndConditions "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/terms_and_conditions"
	graphBetaDeviceManagementTermsAndConditionsAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/terms_and_conditions_assignment"
	graphBetaDeviceManagementWindowsAutopilotDeploymentProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_deployment_profile"
	graphBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_deployment_profile_assignment"
	graphBetaDeviceManagementWindowsAutopilotDevicePreparationPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_device_preparation_policy"
	graphBetaDeviceManagementWindowsDriverUpdateInventory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_driver_update_inventory"
	graphBetaDeviceManagementWindowsDriverUpdateProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_driver_update_profile"
	graphBetaDeviceManagementWindowsDriverUpdateProfileAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_driver_update_profile_assignment"
	graphBetaDeviceManagementWindowsFeatureUpdateProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_feature_update_profile"
	graphBetaDeviceManagementWindowsFeatureUpdateProfileAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_feature_update_profile_assignment"
	graphBetaDeviceManagementWindowsPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_platform_script"
	graphBetaDeviceManagementWindowsQualityExpeditePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy"
	graphBetaDeviceManagementWindowsQualityUpdatePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_quality_update_policy"
	graphBetaDeviceManagementWindowsQualityUpdatePolicyAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_quality_update_policy_assignment"
	graphBetaDeviceManagementWindowsRemediationScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_remediation_script"
	graphBetaDeviceManagementWindowsRemediationScriptAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_remediation_script_assignment"

	// Graph Beta - Identity and Access resources

	"github.com/hashicorp/terraform-plugin-framework/resource"

	// Graph Beta - User resources
	graphBetaUsersUserLicenseAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/users/graph_beta/license_assignment"
	graphBetaUsersUser "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/users/graph_beta/user"

	// Graph Beta - Group resources
	graphBetaGroup "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group"
	graphBetaGroupMemberAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_member_assignment"
	graphBetaGroupOwnerAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_owner_assignment"
	graphBetaGroupLicenseAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/license_assignment"

	// Graph Beta - M365 Admin Centre
	graphBetaM365AdminBrowserSite "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/m365_admin/graph_beta/browser_site"
	graphBetaM365AdminBrowserSiteList "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/m365_admin/graph_beta/browser_site_list"
	graphDeviceM365AdminM365AppsInstallationOptions "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/m365_admin/graph_beta/m365_apps_installation_options"

	// TODO current broken due to how the sdk builds time fields
	//graphBetaDeviceAndAppManagementWindowsUpdateRing "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/windows_update_ring"

	// Graph v1.0 - Intune resources
	graphDeviceAndAppManagementCloudPcDeviceImage "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_v1.0/cloud_pc_device_image"
	graphDeviceAndAppManagementCloudPcProvisioningPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_v1.0/cloud_pc_provisioning_policy"
	graphDeviceAndAppManagementCloudPcUserSetting "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_v1.0/cloud_pc_user_setting"
	graphDeviceManagementDeviceConfigurationAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_v1.0/device_configuration_assignment"
)

// Resources returns a slice of functions that each return a resource.Resource.
// This function is a method of the M365Provider type and takes a context.Context as an argument.
// The returned slice is intended to hold the Microsoft 365 provider resources.
//
// Parameters:
//   - ctx: The context for controlling cancellation and timeout.
//
// Returns:
//
//	[]func() resource.Resource: A slice of functions, each returning a resource.Resource.
//
// Resources returns a slice of functions that each return a resource.Resource.
func (p *M365Provider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		// Graph Beta - Device & app management
		graphBetaDeviceAndAppManagementApplicationCategory.NewApplicationCategoryResource,
		graphBetaDeviceAndAppManagementAppAssignment.NewMobileAppAssignmentResource,
		graphBetaDeviceAndAppManagementMacOSDmgApp.NewMacOSDmgAppResource,
		graphBetaDeviceAndAppManagementMacOSLobApp.NewMacOSLobAppResource,
		graphBetaDeviceAndAppManagementMacOSPKGApp.NewMacOSPKGAppResource,
		graphBetaDeviceAndAppManagementWinGetApp.NewWinGetAppResource,
		// Graph Beta - Device management
		graphBetaDeviceManagementAssignmentFilter.NewAssignmentFilterResource,
		graphBetaDeviceManagementAppleUserInitiatedEnrollmentProfileAssignment.NewAppleUserInitiatedEnrollmentProfileAssignmentResource,
		graphBetaDeviceManagementDeviceCategory.NewDeviceCategoryResource,
		graphBetaDeviceManagementDeviceEnrollmentLimitConfiguration.NewDeviceEnrollmentLimitConfigurationResource,
		graphBetaDeviceManagementDeviceEnrollmentNotificationConfiguration.NewDeviceEnrollmentNotificationConfigurationResource,
		graphBetaDeviceManagementEndpointPrivilegeManagement.NewEndpointPrivilegeManagementResource,
		graphBetaDeviceManagementLinuxPlatformScript.NewLinuxPlatformScriptResource,
		graphBetaDeviceManagementMacOSPlatformScript.NewMacOSPlatformScriptResource,
		graphBetaDeviceManagementMacOSSoftwareUpdateConfiguration.NewMacOSSoftwareUpdateConfigurationResource,
		graphBetaDeviceManagementManagedDeviceCleanupRule.NewManagedDeviceCleanupRuleResource,
		graphBetaDeviceManagementOperationApprovalPolicy.NewOperationApprovalPolicyResource,
		graphBetaDeviceManagementRBACResourceOperation.NewRBACResourceOperationResource,
		graphBetaDeviceManagementReuseablePolicySettings.NewReuseablePolicySettingsResource,
		graphBetaDeviceManagementRoleDefinition.NewRoleDefinitionResource,
		graphBetaDeviceManagementRoleAssignment.NewRoleDefinitionAssignmentResource,
		graphBetaDeviceManagementRoleScopeTag.NewRoleScopeTagResource,
		graphBetaDeviceManagementSettingsCatalog.NewSettingsCatalogResource,
		graphBetaDeviceManagementSettingsCatalogJson.NewSettingsCatalogJsonResource,
		graphBetaDeviceManagementSettingsCatalogTemplateJson.NewDeviceManagementTemplateJsonResource,
		graphBetaDeviceManagementConfigurationPolicyAssignment.NewDeviceManagementConfigurationPolicyAssignmentResource,
		graphBetaDeviceManagementTermsAndConditions.NewTermsAndConditionsResource,
		graphBetaDeviceManagementTermsAndConditionsAssignment.NewTermsAndConditionsAssignmentResource,
		graphBetaDeviceManagementWindowsAutopilotDeploymentProfile.NewWindowsAutopilotDeploymentProfileResource,
		graphBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment.NewWindowsAutopilotDeploymentProfileAssignmentResource,
		graphBetaDeviceManagementWindowsAutopilotDevicePreparationPolicy.NewWindowsAutopilotDevicePreparationPolicyResource,
		graphBetaDeviceManagementWindowsDriverUpdateProfile.NewWindowsDriverUpdateProfileResource,
		graphBetaDeviceManagementWindowsDriverUpdateProfileAssignment.NewWindowsDriverUpdateProfileAssignmentResource,
		graphBetaDeviceManagementWindowsDriverUpdateInventory.NewWindowsDriverUpdateInventoryResource,
		graphBetaDeviceManagementWindowsFeatureUpdateProfileAssignment.NewWindowsFeatureUpdateProfileAssignmentResource,
		graphBetaDeviceManagementWindowsFeatureUpdateProfile.NewWindowsFeatureUpdateProfileResource,
		graphBetaDeviceManagementWindowsPlatformScript.NewWindowsPlatformScriptResource,
		graphBetaDeviceManagementWindowsRemediationScript.NewDeviceHealthScriptResource,
		graphBetaDeviceManagementWindowsRemediationScriptAssignment.NewDeviceHealthScriptAssignmentResource,
		graphBetaDeviceManagementWindowsQualityExpeditePolicy.NewWindowsQualityUpdateExpeditePolicyResource,
		graphBetaDeviceManagementWindowsQualityUpdatePolicyAssignment.NewWindowsQualityUpdateProfileAssignmentResource,
		graphBetaDeviceManagementWindowsQualityUpdatePolicy.NewWindowsQualityUpdatePolicyResource,
		//graphBetaDeviceAndAppManagementWindowsUpdateRing.NewWindowsUpdateRingResource,

		// Graph Beta - Identity and Access resources
		//graphBetaIdentityAndAccessConditionalAccessPolicy.NewConditionalAccessPolicyResource,

		// Graph Beta - User resources
		graphBetaUsersUserLicenseAssignment.NewUserLicenseAssignmentResource,
		graphBetaUsersUser.NewUserResource,

		// Graph Beta - Group resources
		graphBetaGroup.NewGroupResource,
		graphBetaGroupMemberAssignment.NewGroupMemberAssignmentResource,
		graphBetaGroupOwnerAssignment.NewGroupOwnerAssignmentResource,
		graphBetaGroupLicenseAssignment.NewGroupLicenseAssignmentResource,

		// Graph Beta - M365 Admin Centre
		graphBetaM365AdminBrowserSite.NewBrowserSiteResource,
		graphBetaM365AdminBrowserSiteList.NewBrowserSiteListResource,

		// Graph v1.0 - Intune resources
		graphDeviceAndAppManagementCloudPcProvisioningPolicy.NewCloudPcProvisioningPolicyResource,
		graphDeviceAndAppManagementCloudPcUserSetting.NewCloudPcUserSettingResource,
		graphDeviceAndAppManagementCloudPcDeviceImage.NewCloudPcDeviceImageResource,
		graphDeviceManagementDeviceConfigurationAssignment.NewDeviceConfigurationAssignmentResource,

		// Graph v1.0 - M365 Admin Centre
		graphDeviceM365AdminM365AppsInstallationOptions.NewM365AppsInstallationOptionsResource,
		// Add microsoft 365 provider resources here

	}
}
