package provider

import (
	"context"

	// Graph Beta - Agents
	graphBetaApplicationsAgentIdentityBlueprint "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/agents/graph_beta/agent_identity_blueprint"
	graphBetaAgentIdentityBlueprintCertificateCredential "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/agents/graph_beta/agent_identity_blueprint_certificate_credential"

	// NOTE: Disabled due to Microsoft Graph API issues - see developer_notes.md in the resource directory
	graphBetaAgentIdentityBlueprintFederatedIdentityCredential "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/agents/graph_beta/agent_identity_blueprint_federated_identity_credential"
	graphBetaAgentIdentityBlueprintIdentifierUri "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/agents/graph_beta/agent_identity_blueprint_identifier_uri"
	graphBetaAgentIdentityBlueprintPasswordCredential "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/agents/graph_beta/agent_identity_blueprint_password_credential"
	graphBetaApplicationsAgentIdentityBlueprintServicePrincipal "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/agents/graph_beta/agent_identity_blueprint_service_principal"

	// Graph Beta - Device & app management
	graphBetaDeviceAndAppManagementAndroidManagedDeviceAppConfigurationPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/android_managed_device_app_configuration_policy"
	graphBetaDeviceAndAppManagementAndroidManagedMobileApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/android_managed_mobile_app"
	graphBetaDeviceAndAppManagementApplicationCategory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/application_category"
	graphBetaDeviceAndAppManagementIOSiPadOSWebClip "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/ios_ipados_web_clip"
	graphBetaDeviceAndAppManagementIOSManagedDeviceAppConfigurationPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/ios_managed_device_app_configuration_policy"
	graphBetaDeviceAndAppManagementIOSManagedMobileApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/ios_managed_mobile_app"
	graphBetaDeviceAndAppManagementIOSStoreApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/ios_store_app"
	graphBetaDeviceAndAppManagementMacOSDmgApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_dmg_app"
	graphBetaDeviceAndAppManagementMacOSLobApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_lob_app"
	graphBetaDeviceAndAppManagementMacOSPKGApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_pkg_app"
	graphBetaDeviceAndAppManagementMacOSVppApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_vpp_app"
	graphBetaDeviceAndAppManagementApplicationAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/mobile_app_assignment"
	graphBetaDeviceAndAppManagementMobileAppSupersedence "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/mobile_app_supersedence"
	graphBetaDeviceAndAppManagementOfficeSuiteApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/office_suite_app"
	graphBetaDeviceAndAppManagementTargetedManagedAppConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/targeted_managed_app_configuration"
	graphBetaDeviceAndAppManagementWin32App "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/win32_app"
	graphBetaDeviceAndAppManagementWindowsManagedMobileApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/windows_managed_mobile_app"
	graphBetaDeviceAndAppManagementWindowsWebApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/windows_web_app"
	graphBetaDeviceAndAppManagementWinGetApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/winget_app"

	// Graph Beta - Device management
	graphBetaDeviceManagementAndroidDeviceOwnerCompliancePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/android_device_owner_compliance_policy"
	graphBetaDeviceManagementAospDeviceOwnerCompliancePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/aosp_device_owner_compliance_policy"
	graphBetaDeviceManagementAppControlForBusinessBuiltInControls "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/app_control_for_business_built_in_controls"
	graphBetaDeviceManagementAppControlForBusinessPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/app_control_for_business_policy"
	graphBetaDeviceManagementAppleConfiguratorEnrollmentPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/apple_configurator_enrollment_policy"
	graphBetaDeviceManagementAppleUserInitiatedEnrollmentProfileAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/apple_user_initiated_enrollment_profile_assignment"
	graphBetaDeviceManagementAssignmentFilter "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/assignment_filter"
	graphBetaDeviceManagementAutopatchGroups "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/autopatch_groups"
	graphBetaDeviceManagementDeviceCategory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_category"
	graphBetaDeviceManagementDeviceComplianceNotificationTemplate "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_compliance_notification_template"
	graphBetaDeviceManagementDeviceEnrollmentLimitConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_enrollment_limit_configuration"
	graphBetaDeviceManagementDeviceEnrollmentNotification "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_enrollment_notification"
	graphBetaDeviceManagementEndpointPrivilegeManagementJson "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/endpoint_privilege_management_json"
	graphBetaDeviceManagementGroupPolicyBooleanValue "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/group_policy_boolean_value"
	graphBetaDeviceManagementGroupPolicyConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/group_policy_configuration"
	graphBetaDeviceManagementGroupPolicyMultiTextValue "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/group_policy_multi_text_value"
	graphBetaDeviceManagementGroupPolicyTextValue "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/group_policy_text_value"
	graphBetaDeviceManagementGroupPolicyUploadedDefinitionFiles "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/group_policy_uploaded_definition_files"
	graphBetaDeviceManagementIntuneBrandingProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/intune_branding_profile"
	graphBetaDeviceManagementIosDeviceCompliancePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/ios_device_compliance_policy"
	graphBetaDeviceManagementLinuxDeviceCompliancePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/linux_device_compliance_policy"
	graphBetaDeviceManagementLinuxDeviceComplianceScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/linux_device_compliance_script"
	graphBetaDeviceManagementLinuxPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/linux_platform_script"
	graphBetaDeviceManagementMacOSCustomAttributeScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_custom_attribute_script"
	graphBetaDeviceManagementMacOSDeviceCompliancePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_device_compliance_policy"
	graphBetaDeviceManagementMacOSDeviceConfigurationTemplates "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_device_configuration_templates"
	graphBetaDeviceManagementMacOSPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_platform_script"
	graphBetaDeviceManagementMacOSSoftwareUpdateConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_software_update_configuration"
	graphBetaDeviceManagementManagedDeviceCleanupRule "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/managed_device_cleanup_rule"
	graphBetaDeviceManagementOperationApprovalPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/operation_approval_policy"
	graphBetaDeviceManagementPolicySet "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/policy_set"
	graphBetaDeviceManagementRBACResourceOperation "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/rbac_resource_operation"
	graphBetaDeviceManagementReuseablePolicySettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/reuseable_policy_settings"
	graphBetaDeviceManagementRoleAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/role_assignment"
	graphBetaDeviceManagementRoleDefinition "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/role_definition"
	graphBetaDeviceManagementRoleScopeTag "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/role_scope_tag"
	graphBetaDeviceManagementSettingsCatalogConfigurationPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_configuration_policy"
	graphBetaDeviceManagementSettingsCatalogConfigurationPolicyJson "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_configuration_policy_json"
	graphBetaDeviceManagementSettingsCatalogTemplateJson "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_template_json"
	graphBetaDeviceManagementTermsAndConditions "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/terms_and_conditions"
	graphBetaDeviceManagementWindowsAutopilotDeploymentProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_deployment_profile"
	graphBetaDeviceManagementWindowsAutopilotDeviceIdentity "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_device_identity"
	graphBetaDeviceManagementWindowsAutopilotDevicePreparationPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_device_preparation_policy"
	graphBetaDeviceManagementWindowsBackupAndRestore "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_backup_and_restore"
	graphBetaDeviceManagementWindowsDeviceCompliancePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_device_compliance_policy"
	graphBetaDeviceManagementWindowsDeviceComplianceScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_device_compliance_script"
	graphBetaDeviceManagementWindowsDriverUpdateInventory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_driver_update_inventory"
	graphBetaDeviceManagementWindowsDriverUpdateProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_driver_update_profile"
	graphBetaDeviceManagementWindowsEnrollmentStatusPage "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_enrollment_status_page"
	graphBetaDeviceManagementWindowsFeatureUpdateProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_feature_update_profile"
	graphBetaDeviceManagementWindowsPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_platform_script"
	graphBetaDeviceManagementWindowsQualityExpeditePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy"
	graphBetaDeviceManagementWindowsQualityUpdatePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_quality_update_policy"
	graphBetaDeviceManagementWindowsRemediationScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_remediation_script"
	graphBetaDeviceManagementWindowsUpdateRing "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_update_ring"

	// Graph Beta - Applications resources
	graphBetaApplicationsIpApplicationSegment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/applications/graph_beta/ip_application_segment"

	// Graph Beta - Identity and Access resources
	graphBetaIdentityAndAccessAttributeSet "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/attribute_set"
	graphBetaIdentityAndAccessAuthenticationContext "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/authentication_context"
	graphBetaIdentityAndAccessAuthenticationStrengthPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/authentication_strength_policy"
	graphBetaIdentityAndAccessConditionalAccessPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/conditional_access_policy"
	graphBetaIdentityAndAccessCustomSecurityAttributeAllowedValue "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/custom_security_attribute_allowed_value"
	graphBetaIdentityAndAccessCustomSecurityAttributeDefinition "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/custom_security_attribute_definition"

	//graphBetaIdentityAndAccessDirectorySettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/directory_settings"
	graphBetaIdentityAndAccessNamedLocation "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/named_location"
	graphBetaIdentityAndAccessNetworkFilteringPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/network_filtering_policy"

	// Graph v1.0 - Identity and Access resources
	graphIdentityAndAccessConditionalAccessTermsOfUse "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_v1.0/conditional_access_terms_of_use"

	"github.com/hashicorp/terraform-plugin-framework/resource"

	// Graph Beta - User resources
	graphBetaUsersUserLicenseAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/users/graph_beta/license_assignment"
	graphBetaUsersUser "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/users/graph_beta/user"
	graphBetaUsersUserMailboxSettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/users/graph_beta/user_mailbox_settings"

	// Graph Beta - Directory resources

	// Graph Beta - Group resources
	graphBetaGroup "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group"
	graphBetaGroupLifecycleExpirationPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_lifecycle_expiration_policy"
	graphBetaGroupLifecycleExpirationPolicyAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_lifecycle_expiration_policy_assignment"
	graphBetaGroupMemberAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_member_assignment"
	graphBetaGroupOwnerAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_owner_assignment"
	graphBetaGroupLicenseAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/license_assignment"

	// Graph Beta - M365 Admin Centre
	graphBetaM365AdminBrowserSite "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/m365_admin/graph_beta/browser_site"
	graphBetaM365AdminBrowserSiteList "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/m365_admin/graph_beta/browser_site_list"
	graphDeviceM365AdminM365AppsInstallationOptions "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/m365_admin/graph_beta/m365_apps_installation_options"

	// Graph Beta - Windows 365 resources
	graphBetaWindows365AzureNetworkConnection "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/azure_network_connection"
	graphBetaWindows365CloudPcAlertRule "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_alert_rule"
	graphBetaWindows365CloudPcDeviceImage "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_device_image"
	graphBetaWindows365CloudPcOrganizationSettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_organization_settings"
	graphBetaWindows365CloudPcProvisioningPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_provisioning_policy"
	graphBetaWindows365CloudPcRoleDefinition "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_role_definition"
	graphBetaWindows365CloudPcUserSetting "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_user_setting"

	// Graph v1.0 - Intune resources
	graphDeviceManagementDeviceConfigurationAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_v1.0/device_configuration_assignment"

	// PowerShell - Microsoft Teams
	powershellMicrosoftTeamsTeamsCallingPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/microsoft_teams/teams_calling_policy"
	powershellMicrosoftTeamsTeamsMeetingPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/microsoft_teams/teams_meeting_policy"
)

// Resources returns a slice of functions that each return a resource.Resource.
// This function is a method of the M365Provider type and takes a context.Context as an argument.
// The returned slice is intended to hold the Microsoft 365 provider resources.
//
// Parameters:
//   - ctx: The context for controlling cancellation and timeout.
//
// Returns:
//
//	[]func() resource.Resource: A slice of functions, each returning a resource.Resource.
//
// Resources returns a slice of functions that each return a resource.Resource.
func (p *M365Provider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		// Agents
		graphBetaApplicationsAgentIdentityBlueprint.NewAgentIdentityBlueprintResource,
		// NOTE: Disabled due to Microsoft Graph API issues - see developer_notes.md in the resource directory
		graphBetaAgentIdentityBlueprintFederatedIdentityCredential.NewAgentIdentityBlueprintFederatedIdentityCredentialResource,
		graphBetaAgentIdentityBlueprintCertificateCredential.NewAgentIdentityBlueprintCertificateCredentialResource,

		graphBetaAgentIdentityBlueprintIdentifierUri.NewAgentIdentityBlueprintIdentifierUriResource,
		graphBetaAgentIdentityBlueprintPasswordCredential.NewAgentIdentityBlueprintPasswordCredentialResource,
		graphBetaApplicationsAgentIdentityBlueprintServicePrincipal.NewAgentIdentityBlueprintServicePrincipalResource,

		// Graph Beta - Device & app management
		graphBetaDeviceAndAppManagementAndroidManagedDeviceAppConfigurationPolicy.NewAndroidManagedDeviceAppConfigurationPolicyResource,
		graphBetaDeviceAndAppManagementApplicationCategory.NewApplicationCategoryResource,
		graphBetaDeviceAndAppManagementApplicationAssignment.NewMobileAppAssignmentResource,
		graphBetaDeviceAndAppManagementIOSStoreApp.NewIOSStoreAppResource,
		graphBetaDeviceAndAppManagementIOSiPadOSWebClip.NewIOSiPadOSWebClipResource,
		graphBetaDeviceAndAppManagementMacOSVppApp.NewMacOSVppAppResource,
		graphBetaDeviceAndAppManagementOfficeSuiteApp.NewOfficeSuiteAppResource,
		graphBetaDeviceAndAppManagementMacOSDmgApp.NewMacOSDmgAppResource,
		graphBetaDeviceAndAppManagementMacOSLobApp.NewMacOSLobAppResource,
		graphBetaDeviceAndAppManagementMacOSPKGApp.NewMacOSPKGAppResource,
		graphBetaDeviceAndAppManagementTargetedManagedAppConfiguration.NewTargetedManagedAppConfigurationResource,
		graphBetaDeviceAndAppManagementMobileAppSupersedence.NewMobileAppSupersedenceResource,
		graphBetaDeviceAndAppManagementWinGetApp.NewWinGetAppResource,
		graphBetaDeviceAndAppManagementWindowsWebApp.NewWindowsWebAppResource,
		graphBetaDeviceAndAppManagementWin32App.NewWin32LobAppResource,
		graphBetaDeviceAndAppManagementAndroidManagedMobileApp.NewAndroidManagedMobileAppResource,
		graphBetaDeviceAndAppManagementIOSManagedMobileApp.NewIOSManagedMobileAppResource,
		graphBetaDeviceAndAppManagementIOSManagedDeviceAppConfigurationPolicy.NewIOSManagedDeviceAppConfigurationPolicyResource,
		graphBetaDeviceAndAppManagementWindowsManagedMobileApp.NewWindowsManagedMobileAppResource,

		// Graph Beta - Device management
		graphBetaDeviceManagementAndroidDeviceOwnerCompliancePolicy.NewAndroidDeviceOwnerCompliancePolicyResource,
		graphBetaDeviceManagementAospDeviceOwnerCompliancePolicy.NewAospDeviceOwnerCompliancePolicyResource,
		graphBetaDeviceManagementAppControlForBusinessBuiltInControls.NewAppControlForBusinessResourceBuiltInControlsResource,
		graphBetaDeviceManagementAppControlForBusinessPolicy.NewAppControlForBusinessPolicyResource,
		graphBetaDeviceManagementAppleConfiguratorEnrollmentPolicy.NewAppleConfiguratorEnrollmentPolicyResource,
		graphBetaDeviceManagementAppleUserInitiatedEnrollmentProfileAssignment.NewAppleUserInitiatedEnrollmentProfileAssignmentResource,
		graphBetaDeviceManagementAssignmentFilter.NewAssignmentFilterResource,
		graphBetaDeviceManagementAutopatchGroups.NewAutopatchGroupsResource,
		graphBetaDeviceManagementDeviceCategory.NewDeviceCategoryResource,
		graphBetaDeviceManagementDeviceEnrollmentLimitConfiguration.NewDeviceEnrollmentLimitConfigurationResource,
		graphBetaDeviceManagementDeviceEnrollmentNotification.NewDeviceEnrollmentNotificationResource,
		graphBetaDeviceManagementEndpointPrivilegeManagementJson.NewEndpointPrivilegeManagementResource,
		graphBetaDeviceManagementGroupPolicyBooleanValue.NewGroupPolicyBooleanValueResource,
		graphBetaDeviceManagementGroupPolicyConfiguration.NewGroupPolicyConfigurationResource,
		graphBetaDeviceManagementGroupPolicyMultiTextValue.NewGroupPolicyMultiTextValueResource,
		graphBetaDeviceManagementGroupPolicyTextValue.NewGroupPolicyTextValueResource,
		graphBetaDeviceManagementGroupPolicyUploadedDefinitionFiles.NewGroupPolicyUploadedDefinitionFileResource,
		graphBetaDeviceManagementIntuneBrandingProfile.NewIntuneBrandingProfileResource,
		graphBetaDeviceManagementLinuxPlatformScript.NewLinuxPlatformScriptResource,
		graphBetaDeviceManagementLinuxDeviceCompliancePolicy.NewLinuxDeviceCompliancePolicyResource,
		graphBetaDeviceManagementLinuxDeviceComplianceScript.NewLinuxDeviceComplianceScriptResource,
		graphBetaDeviceManagementIosDeviceCompliancePolicy.NewIosDeviceCompliancePolicyResource,
		graphBetaDeviceManagementMacOSDeviceConfigurationTemplates.NewMacosDeviceConfigurationTemplatesResource,
		graphBetaDeviceManagementMacOSPlatformScript.NewMacOSPlatformScriptResource,
		graphBetaDeviceManagementMacOSDeviceCompliancePolicy.NewMacosDeviceCompliancePolicyResource,
		graphBetaDeviceManagementMacOSCustomAttributeScript.NewDeviceCustomAttributeShellScriptResource,
		graphBetaDeviceManagementMacOSSoftwareUpdateConfiguration.NewMacOSSoftwareUpdateConfigurationResource,
		graphBetaDeviceManagementManagedDeviceCleanupRule.NewManagedDeviceCleanupRuleResource,
		graphBetaDeviceManagementOperationApprovalPolicy.NewOperationApprovalPolicyResource,
		graphBetaDeviceManagementPolicySet.NewPolicySetResource,
		graphBetaDeviceManagementRBACResourceOperation.NewRBACResourceOperationResource,
		graphBetaDeviceManagementReuseablePolicySettings.NewReuseablePolicySettingsResource,
		graphBetaDeviceManagementRoleDefinition.NewRoleDefinitionResource,
		graphBetaDeviceManagementRoleAssignment.NewRoleAssignmentResource,
		graphBetaDeviceManagementRoleScopeTag.NewRoleScopeTagResource,
		graphBetaDeviceManagementDeviceComplianceNotificationTemplate.NewDeviceComplianceNotificationTemplateResource,
		graphBetaDeviceManagementSettingsCatalogConfigurationPolicy.NewSettingsCatalogResource,
		graphBetaDeviceManagementSettingsCatalogConfigurationPolicyJson.NewSettingsCatalogJsonResource,
		graphBetaDeviceManagementSettingsCatalogTemplateJson.NewDeviceManagementTemplateJsonResource,
		graphBetaDeviceManagementTermsAndConditions.NewTermsAndConditionsResource,
		graphBetaDeviceManagementWindowsAutopilotDeploymentProfile.NewWindowsAutopilotDeploymentProfileResource,
		graphBetaDeviceManagementWindowsAutopilotDeviceIdentity.NewWindowsAutopilotDeviceIdentityResource,
		graphBetaDeviceManagementWindowsAutopilotDevicePreparationPolicy.NewWindowsAutopilotDevicePreparationPolicyResource,
		graphBetaDeviceManagementWindowsDeviceCompliancePolicy.NewWindowsDeviceCompliancePolicyResource,
		graphBetaDeviceManagementWindowsDeviceComplianceScript.NewDeviceComplianceScriptResource,
		graphBetaDeviceManagementWindowsDriverUpdateProfile.NewWindowsDriverUpdateProfileResource,
		graphBetaDeviceManagementWindowsDriverUpdateInventory.NewWindowsDriverUpdateInventoryResource,
		graphBetaDeviceManagementWindowsEnrollmentStatusPage.NewWindowsEnrollmentStatusPageResource,
		graphBetaDeviceManagementWindowsFeatureUpdateProfile.NewWindowsFeatureUpdateProfileResource,
		graphBetaDeviceManagementWindowsPlatformScript.NewWindowsPlatformScriptResource,
		graphBetaDeviceManagementWindowsRemediationScript.NewDeviceHealthScriptResource,
		graphBetaDeviceManagementWindowsQualityExpeditePolicy.NewWindowsQualityUpdateExpeditePolicyResource,
		graphBetaDeviceManagementWindowsQualityUpdatePolicy.NewWindowsQualityUpdatePolicyResource,
		graphBetaDeviceManagementWindowsUpdateRing.NewWindowsUpdateRingResource,
		graphBetaDeviceManagementWindowsBackupAndRestore.NewWindowsBackupAndRestoreResource,

		// Graph Beta - Applications resources
		graphBetaApplicationsIpApplicationSegment.NewIpApplicationSegmentResource,

		// Graph Beta - Identity and Access resources
		graphBetaIdentityAndAccessAttributeSet.NewAttributeSetResource,
		graphBetaIdentityAndAccessAuthenticationContext.NewAuthenticationContextResource,
		graphBetaIdentityAndAccessAuthenticationStrengthPolicy.NewAuthenticationStrengthPolicyResource,
		graphBetaIdentityAndAccessCustomSecurityAttributeAllowedValue.NewCustomSecurityAttributeAllowedValueResource,
		graphBetaIdentityAndAccessCustomSecurityAttributeDefinition.NewCustomSecurityAttributeDefinitionResource,
		graphBetaIdentityAndAccessConditionalAccessPolicy.NewConditionalAccessPolicyResource,
		//graphBetaIdentityAndAccessDirectorySettings.NewDirectorySettingsResource,
		graphBetaIdentityAndAccessNetworkFilteringPolicy.NewNetworkFilteringPolicyResource,
		graphBetaIdentityAndAccessNamedLocation.NewNamedLocationResource,

		// Graph Beta - User resources
		graphBetaUsersUserLicenseAssignment.NewUserLicenseAssignmentResource,
		graphBetaUsersUser.NewUserResource,
		graphBetaUsersUserMailboxSettings.NewUserMailboxSettingsResource,

		// Graph Beta - Group resources
		graphBetaGroup.NewGroupResource,
		graphBetaGroupLifecycleExpirationPolicy.NewGroupLifecycleExpirationPolicyResource,
		graphBetaGroupLifecycleExpirationPolicyAssignment.NewGroupLifecycleExpirationPolicyAssignmentResource,
		graphBetaGroupMemberAssignment.NewGroupMemberAssignmentResource,
		graphBetaGroupOwnerAssignment.NewGroupOwnerAssignmentResource,
		graphBetaGroupLicenseAssignment.NewGroupLicenseAssignmentResource,

		// Graph Beta - M365 Admin Centre
		graphBetaM365AdminBrowserSite.NewBrowserSiteResource,
		graphBetaM365AdminBrowserSiteList.NewBrowserSiteListResource,

		// Graph Beta - Windows 365 resources
		graphBetaWindows365CloudPcProvisioningPolicy.NewCloudPcProvisioningPolicyResource,
		graphBetaWindows365CloudPcUserSetting.NewCloudPcUserSettingResource,
		graphBetaWindows365CloudPcOrganizationSettings.NewCloudPcOrganizationSettingsResource,
		graphBetaWindows365AzureNetworkConnection.NewCloudPcOnPremisesConnectionResource,
		graphBetaWindows365CloudPcDeviceImage.NewCloudPcDeviceImageResource,
		graphBetaWindows365CloudPcAlertRule.NewCloudPcAlertRuleResource,
		graphBetaWindows365CloudPcRoleDefinition.NewRoleDefinitionResource,

		// Graph v1.0 - Identity and Access resources
		graphIdentityAndAccessConditionalAccessTermsOfUse.NewConditionalAccessTermsOfUseResource,

		// Graph v1.0 - Intune resources
		graphDeviceManagementDeviceConfigurationAssignment.NewDeviceConfigurationAssignmentResource,

		// Graph v1.0 - M365 Admin Centre
		graphDeviceM365AdminM365AppsInstallationOptions.NewM365AppsInstallationOptionsResource,

		// PowerShell - Microsoft Teams
		powershellMicrosoftTeamsTeamsCallingPolicy.NewTeamsCallingPolicyResource,
		powershellMicrosoftTeamsTeamsMeetingPolicy.NewTeamsMeetingPolicyResource,

		// Add microsoft 365 provider resources here
	}
}
