package provider

import (
	"context"
	// Graph Beta - Device & app management
	graphBetaDeviceAndAppManagementApplicationCategory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/application_category"
	graphBetaDeviceAndAppManagementIOSiPadOSWebClip "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/ios_ipados_web_clip"
	graphBetaDeviceAndAppManagementIOSStoreApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/ios_store_app"
	graphBetaDeviceAndAppManagementMacOSDmgApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_dmg_app"
	graphBetaDeviceAndAppManagementMacOSLobApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_lob_app"
	graphBetaDeviceAndAppManagementMacOSPKGApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_pkg_app"
	graphBetaDeviceAndAppManagementMacOSVppApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/macos_vpp_app"
	graphBetaDeviceAndAppManagementApplicationAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/mobile_app_assignment"
	graphBetaDeviceAndAppManagementMobileAppSupersedence "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/mobile_app_supersedence"
	graphBetaDeviceAndAppManagementWin32App "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/win32_app"
	graphBetaDeviceAndAppManagementWindowsWebApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/windows_web_app"
	graphBetaDeviceAndAppManagementWinGetApp "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/winget_app"

	// Graph Beta - Device management
	graphBetaDeviceManagementAppleUserInitiatedEnrollmentProfileAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/apple_user_initiated_enrollment_profile_assignment"
	graphBetaDeviceManagementAssignmentFilter "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/assignment_filter"
	graphBetaDeviceManagementDeviceCategory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_category"
	graphBetaDeviceManagementDeviceEnrollmentLimitConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_enrollment_limit_configuration"
	graphBetaDeviceManagementDeviceEnrollmentNotificationConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/device_enrollment_notification_configuration"
	graphBetaDeviceManagementEndpointPrivilegeManagement "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/endpoint_privilege_management"
	graphBetaDeviceManagementLinuxPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/linux_platform_script"
	graphBetaDeviceManagementMacOSCustomAttributeScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_custom_attribute_script"
	graphBetaDeviceManagementMacOSCustomAttributeScriptAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_custom_attribute_script_assignment"
	graphBetaDeviceManagementMacOSPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_platform_script"
	graphBetaDeviceManagementMacOSPlatformScriptAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_platform_script_assignment"
	graphBetaDeviceManagementMacOSSoftwareUpdateConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/macos_software_update_configuration"
	graphBetaDeviceManagementManagedDeviceCleanupRule "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/managed_device_cleanup_rule"
	graphBetaDeviceManagementOperationApprovalPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/operation_approval_policy"
	graphBetaDeviceManagementRBACResourceOperation "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/rbac_resource_operation"
	graphBetaDeviceManagementReuseablePolicySettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/reuseable_policy_settings"
	graphBetaDeviceManagementRoleAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/role_assignment"
	graphBetaDeviceManagementRoleDefinition "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/role_definition"
	graphBetaDeviceManagementRoleScopeTag "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/role_scope_tag"
	graphBetaDeviceManagementConfigurationPolicyAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_assignment"
	graphBetaDeviceManagementSettingsCatalogConfigurationPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_configuration_policy"
	graphBetaDeviceManagementSettingsCatalogConfigurationPolicyJson "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_configuration_policy_json"
	graphBetaDeviceManagementSettingsCatalogTemplateJson "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/settings_catalog_template_json"
	graphBetaDeviceManagementTermsAndConditions "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/terms_and_conditions"
	graphBetaDeviceManagementTermsAndConditionsAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/terms_and_conditions_assignment"
	graphBetaDeviceManagementWindowsAutopilotDeploymentProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_deployment_profile"
	graphBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_deployment_profile_assignment"
	graphBetaDeviceManagementWindowsAutopilotDeviceIdentity "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_device_identity"
	graphBetaDeviceManagementWindowsAutopilotDevicePreparationPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_autopilot_device_preparation_policy"
	graphBetaDeviceManagementWindowsDriverUpdateInventory "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_driver_update_inventory"
	graphBetaDeviceManagementWindowsDriverUpdateProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_driver_update_profile"
	graphBetaDeviceManagementWindowsDriverUpdateProfileAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_driver_update_profile_assignment"
	graphBetaDeviceManagementWindowsFeatureUpdateProfile "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_feature_update_profile"
	graphBetaDeviceManagementWindowsFeatureUpdateProfileAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_feature_update_profile_assignment"
	graphBetaDeviceManagementWindowsPlatformScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_platform_script"
	graphBetaDeviceManagementWindowsPlatformScriptAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_platform_script_assignment"
	graphBetaDeviceManagementWindowsQualityExpeditePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_quality_update_expedite_policy"
	graphBetaDeviceManagementWindowsQualityUpdatePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_quality_update_policy"
	graphBetaDeviceManagementWindowsQualityUpdatePolicyAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_quality_update_policy_assignment"
	graphBetaDeviceManagementWindowsRemediationScript "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_remediation_script"
	graphBetaDeviceManagementWindowsRemediationScriptAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_beta/windows_remediation_script_assignment"

	// Graph Beta - Identity and Access resources
	graphBetaIdentityAndAccessConditionalAccessPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/identity_and_access/graph_beta/conditional_access_policy"

	"github.com/hashicorp/terraform-plugin-framework/resource"

	// Graph Beta - User resources
	graphBetaUsersUserLicenseAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/users/graph_beta/license_assignment"
	graphBetaUsersUser "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/users/graph_beta/user"

	// Graph Beta - Group resources
	graphBetaGroup "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group"
	graphBetaGroupLifecyclePolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_lifecycle_policy"
	graphBetaGroupMemberAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_member_assignment"
	graphBetaGroupOwnerAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_owner_assignment"
	graphBetaGroupSettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/group_settings"
	graphBetaGroupLicenseAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/license_assignment"
	graphBetaTenantWideGroupSettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/groups/graph_beta/tenant_wide_group_settings"

	// Graph Beta - M365 Admin Centre
	graphBetaM365AdminBrowserSite "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/m365_admin/graph_beta/browser_site"
	graphBetaM365AdminBrowserSiteList "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/m365_admin/graph_beta/browser_site_list"
	graphDeviceM365AdminM365AppsInstallationOptions "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/m365_admin/graph_beta/m365_apps_installation_options"

	// TODO current broken due to how the sdk builds time fields
	//graphBetaDeviceAndAppManagementWindowsUpdateRing "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_beta/windows_update_ring"

	// Graph Beta - Windows 365 resources
	graphBetaWindows365AzureNetworkConnection "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/azure_network_connection"
	graphBetaWindows365CloudPcAlertRule "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_alert_rule"
	graphBetaWindows365CloudPcDeviceImage "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_device_image"
	graphBetaWindows365CloudPcOrganizationSettings "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_organization_settings"
	graphBetaWindows365CloudPcProvisioningPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/cloud_pc_provisioning_policy"
	graphBetaWindows365UserSetting "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/windows_365/graph_beta/user_setting"

	// Graph v1.0 - Device & app management
	graphV1DeviceAndAppManagementIOSMobileAppConfiguration "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_and_app_management/graph_v1.0/ios_mobile_app_configuration"

	// Graph v1.0 - Intune resources
	graphDeviceManagementDeviceConfigurationAssignment "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/device_management/graph_v1.0/device_configuration_assignment"

	// PowerShell - Microsoft Teams
	powershellMicrosoftTeamsTeamsCallingPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/microsoft_teams/teams_calling_policy"
	powershellMicrosoftTeamsTeamsMeetingPolicy "github.com/deploymenttheory/terraform-provider-microsoft365/internal/services/resources/microsoft_teams/teams_meeting_policy"
)

// Resources returns a slice of functions that each return a resource.Resource.
// This function is a method of the M365Provider type and takes a context.Context as an argument.
// The returned slice is intended to hold the Microsoft 365 provider resources.
//
// Parameters:
//   - ctx: The context for controlling cancellation and timeout.
//
// Returns:
//
//	[]func() resource.Resource: A slice of functions, each returning a resource.Resource.
//
// Resources returns a slice of functions that each return a resource.Resource.
func (p *M365Provider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		// Graph Beta - Device & app management
		graphBetaDeviceAndAppManagementApplicationCategory.NewApplicationCategoryResource,
		graphBetaDeviceAndAppManagementApplicationAssignment.NewMobileAppAssignmentResource,
		graphBetaDeviceAndAppManagementIOSStoreApp.NewIOSStoreAppResource,
		graphBetaDeviceAndAppManagementIOSiPadOSWebClip.NewIOSiPadOSWebClipResource,
		graphBetaDeviceAndAppManagementMacOSVppApp.NewMacOSVppAppResource,
		graphBetaDeviceAndAppManagementMacOSDmgApp.NewMacOSDmgAppResource,
		graphBetaDeviceAndAppManagementMacOSLobApp.NewMacOSLobAppResource,
		graphBetaDeviceAndAppManagementMacOSPKGApp.NewMacOSPKGAppResource,
		graphBetaDeviceAndAppManagementMobileAppSupersedence.NewMobileAppSupersedenceResource,
		graphBetaDeviceAndAppManagementWinGetApp.NewWinGetAppResource,
		graphBetaDeviceAndAppManagementWindowsWebApp.NewWindowsWebAppResource,
		graphBetaDeviceAndAppManagementWin32App.NewWin32LobAppResource,

		// Graph Beta - Device management
		graphBetaDeviceManagementAssignmentFilter.NewAssignmentFilterResource,
		graphBetaDeviceManagementAppleUserInitiatedEnrollmentProfileAssignment.NewAppleUserInitiatedEnrollmentProfileAssignmentResource,
		graphBetaDeviceManagementDeviceCategory.NewDeviceCategoryResource,
		graphBetaDeviceManagementDeviceEnrollmentLimitConfiguration.NewDeviceEnrollmentLimitConfigurationResource,
		graphBetaDeviceManagementDeviceEnrollmentNotificationConfiguration.NewDeviceEnrollmentNotificationConfigurationResource,
		graphBetaDeviceManagementEndpointPrivilegeManagement.NewEndpointPrivilegeManagementResource,
		graphBetaDeviceManagementLinuxPlatformScript.NewLinuxPlatformScriptResource,
		graphBetaDeviceManagementMacOSPlatformScript.NewMacOSPlatformScriptResource,
		graphBetaDeviceManagementMacOSPlatformScriptAssignment.NewMacosPlatformScriptAssignmentResource,
		graphBetaDeviceManagementMacOSCustomAttributeScript.NewDeviceCustomAttributeShellScriptResource,
		graphBetaDeviceManagementMacOSCustomAttributeScriptAssignment.NewMacosCustomAttributeScriptAssignmentResource,
		graphBetaDeviceManagementMacOSSoftwareUpdateConfiguration.NewMacOSSoftwareUpdateConfigurationResource,
		graphBetaDeviceManagementManagedDeviceCleanupRule.NewManagedDeviceCleanupRuleResource,
		graphBetaDeviceManagementOperationApprovalPolicy.NewOperationApprovalPolicyResource,
		graphBetaDeviceManagementRBACResourceOperation.NewRBACResourceOperationResource,
		graphBetaDeviceManagementReuseablePolicySettings.NewReuseablePolicySettingsResource,
		graphBetaDeviceManagementRoleDefinition.NewRoleDefinitionResource,
		graphBetaDeviceManagementRoleAssignment.NewRoleDefinitionAssignmentResource,
		graphBetaDeviceManagementRoleScopeTag.NewRoleScopeTagResource,
		graphBetaDeviceManagementSettingsCatalogConfigurationPolicy.NewSettingsCatalogResource,
		graphBetaDeviceManagementSettingsCatalogConfigurationPolicyJson.NewSettingsCatalogJsonResource,
		graphBetaDeviceManagementSettingsCatalogTemplateJson.NewDeviceManagementTemplateJsonResource,
		graphBetaDeviceManagementConfigurationPolicyAssignment.NewDeviceManagementConfigurationPolicyAssignmentResource,
		graphBetaDeviceManagementTermsAndConditions.NewTermsAndConditionsResource,
		graphBetaDeviceManagementTermsAndConditionsAssignment.NewTermsAndConditionsAssignmentResource,
		graphBetaDeviceManagementWindowsAutopilotDeploymentProfile.NewWindowsAutopilotDeploymentProfileResource,
		graphBetaDeviceManagementWindowsAutopilotDeploymentProfileAssignment.NewWindowsAutopilotDeploymentProfileAssignmentResource,
		graphBetaDeviceManagementWindowsAutopilotDeviceIdentity.NewWindowsAutopilotDeviceIdentityResource,
		graphBetaDeviceManagementWindowsAutopilotDevicePreparationPolicy.NewWindowsAutopilotDevicePreparationPolicyResource,
		graphBetaDeviceManagementWindowsDriverUpdateProfile.NewWindowsDriverUpdateProfileResource,
		graphBetaDeviceManagementWindowsDriverUpdateProfileAssignment.NewWindowsDriverUpdateProfileAssignmentResource,
		graphBetaDeviceManagementWindowsDriverUpdateInventory.NewWindowsDriverUpdateInventoryResource,
		graphBetaDeviceManagementWindowsFeatureUpdateProfileAssignment.NewWindowsFeatureUpdateProfileAssignmentResource,
		graphBetaDeviceManagementWindowsFeatureUpdateProfile.NewWindowsFeatureUpdateProfileResource,
		graphBetaDeviceManagementWindowsPlatformScript.NewWindowsPlatformScriptResource,
		graphBetaDeviceManagementWindowsPlatformScriptAssignment.NewWindowsPlatformScriptAssignmentResource,
		graphBetaDeviceManagementWindowsRemediationScript.NewDeviceHealthScriptResource,
		graphBetaDeviceManagementWindowsRemediationScriptAssignment.NewDeviceHealthScriptAssignmentResource,
		graphBetaDeviceManagementWindowsQualityExpeditePolicy.NewWindowsQualityUpdateExpeditePolicyResource,
		graphBetaDeviceManagementWindowsQualityUpdatePolicyAssignment.NewWindowsQualityUpdateProfileAssignmentResource,
		graphBetaDeviceManagementWindowsQualityUpdatePolicy.NewWindowsQualityUpdatePolicyResource,
		//graphBetaDeviceAndAppManagementWindowsUpdateRing.NewWindowsUpdateRingResource,

		// Graph Beta - Identity and Access resources
		graphBetaIdentityAndAccessConditionalAccessPolicy.NewConditionalAccessPolicyResource,

		// Graph Beta - User resources
		graphBetaUsersUserLicenseAssignment.NewUserLicenseAssignmentResource,
		graphBetaUsersUser.NewUserResource,

		// Graph Beta - Group resources
		graphBetaGroup.NewGroupResource,
		graphBetaGroupLifecyclePolicy.NewGroupLifecyclePolicyResource,
		graphBetaGroupMemberAssignment.NewGroupMemberAssignmentResource,
		graphBetaGroupOwnerAssignment.NewGroupOwnerAssignmentResource,
		graphBetaGroupSettings.NewGroupSettingsResource,
		graphBetaGroupLicenseAssignment.NewGroupLicenseAssignmentResource,
		graphBetaTenantWideGroupSettings.NewTenantWideGroupSettingsResource,

		// Graph Beta - M365 Admin Centre
		graphBetaM365AdminBrowserSite.NewBrowserSiteResource,
		graphBetaM365AdminBrowserSiteList.NewBrowserSiteListResource,

		// Graph Beta - Windows 365 resources
		graphBetaWindows365CloudPcProvisioningPolicy.NewCloudPcProvisioningPolicyResource,
		graphBetaWindows365UserSetting.NewCloudPcUserSettingResource,
		graphBetaWindows365CloudPcOrganizationSettings.NewCloudPcOrganizationSettingsResource,
		graphBetaWindows365AzureNetworkConnection.NewCloudPcOnPremisesConnectionResource,
		graphBetaWindows365CloudPcDeviceImage.NewCloudPcDeviceImageResource,
		graphBetaWindows365CloudPcAlertRule.NewCloudPcAlertRuleResource,

		// Graph v1.0 - Device & app management
		graphV1DeviceAndAppManagementIOSMobileAppConfiguration.NewIOSMobileAppConfigurationResource,

		// Graph v1.0 - Intune resources
		graphDeviceManagementDeviceConfigurationAssignment.NewDeviceConfigurationAssignmentResource,

		// Graph v1.0 - M365 Admin Centre
		graphDeviceM365AdminM365AppsInstallationOptions.NewM365AppsInstallationOptionsResource,

		// PowerShell - Microsoft Teams
		powershellMicrosoftTeamsTeamsCallingPolicy.NewTeamsCallingPolicyResource,
		powershellMicrosoftTeamsTeamsMeetingPolicy.NewTeamsMeetingPolicyResource,

		// Add microsoft 365 provider resources here
	}
}
