package graphBetaApplicationsAgentIdentityBlueprint

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/tfsdk"
)

// agentIdentityBlueprintConsistencyPredicate returns a consistency predicate for ReadWithRetry
// that verifies the agent identity blueprint resource write has propagated across Microsoft Entra
// replicas before accepting the read as authoritative.
//
// The predicate compares all user-specified mutable fields from the expected plan against the
// state returned by the read. A stale replica returns the pre-write version of the object,
// causing at least one field to differ and triggering a retry.
//
// app_id is Computed — generated by Entra on creation — and is checked to confirm the replica
// has the full object representation. It is not a mutable field.
//
// See: https://devblogs.microsoft.com/identity/designing-for-eventual-consistency-for-microsoft-entra/
func agentIdentityBlueprintConsistencyPredicate(expected *AgentIdentityBlueprintResourceModel) func(ctx context.Context, state tfsdk.State) bool {
	return func(ctx context.Context, state tfsdk.State) bool {
		var actual AgentIdentityBlueprintResourceModel
		if diags := state.Get(ctx, &actual); diags.HasError() {
			return false
		}

		if actual.ID.IsNull() || actual.ID.IsUnknown() || actual.ID.ValueString() == "" {
			return false
		}

		// app_id is Computed — the client ID generated by Entra, never set from plan.
		// Its presence confirms the replica has the full object.
		if actual.AppId.IsNull() || actual.AppId.IsUnknown() || actual.AppId.ValueString() == "" {
			return false
		}

		// Compare all user-specified mutable fields. If any field set in the plan does not
		// match the read-back state, the responding replica has not yet received the write.
		if !actual.DisplayName.Equal(expected.DisplayName) {
			return false
		}
		if !expected.Description.IsNull() && !expected.Description.IsUnknown() {
			if !actual.Description.Equal(expected.Description) {
				return false
			}
		}
		if !expected.SignInAudience.IsNull() && !expected.SignInAudience.IsUnknown() {
			if !actual.SignInAudience.Equal(expected.SignInAudience) {
				return false
			}
		}
		if !expected.Tags.IsNull() && !expected.Tags.IsUnknown() {
			if !actual.Tags.Equal(expected.Tags) {
				return false
			}
		}
		if !expected.SponsorUserIds.IsNull() && !expected.SponsorUserIds.IsUnknown() {
			if !actual.SponsorUserIds.Equal(expected.SponsorUserIds) {
				return false
			}
		}
		if !expected.OwnerUserIds.IsNull() && !expected.OwnerUserIds.IsUnknown() {
			if !actual.OwnerUserIds.Equal(expected.OwnerUserIds) {
				return false
			}
		}

		return true
	}
}
