resource "microsoft365_powershell_microsoft_teams_teams_calling_policy" "example" {
  id                                       = "ExampleCallingPolicy"
  ai_interpreter                           = "Enabled"
  allow_call_forwarding_to_phone           = true
  allow_call_forwarding_to_user            = true
  allow_call_groups                        = true
  allow_call_redirect                      = "Enabled"
  allow_cloud_recording_for_calls          = true
  allow_delegation                         = true
  allow_private_calling                    = true
  allow_sip_devices_calling                = false
  allow_transcription_for_calling          = true
  allow_voicemail                          = "AlwaysEnabled"
  allow_web_pstn_calling                   = false
  auto_answer_enabled_type                 = "Enabled"
  busy_on_busy_enabled_type                = "Enabled"
  calling_spend_user_limit                 = 1000
  call_recording_expiration_days           = 30
  copilot                                  = "Enabled"
  description                              = "Example Teams Calling Policy for demonstration."
  enable_spend_limits                      = true
  enable_web_pstn_media_bypass             = false
  inbound_federated_call_routing_treatment = "RegularIncoming"
  inbound_pstn_call_routing_treatment      = "RegularIncoming"
  live_captions_enabled_type_for_calling   = "DisabledUserOverride"
  music_on_hold_enabled_type               = "Enabled"
  popout_app_path_for_incoming_pstn_calls  = "https://example.com/call"
  popout_for_incoming_pstn_calls           = "Enabled"
  prevent_toll_bypass                      = false
  spam_filtering_enabled_type              = "Enabled"
  voice_simulation_in_interpreter          = "Enabled"
  real_time_text                           = "Enabled"
} 