name: Comment Failure

on:
  # This file is reused, and called from other workflows
  workflow_call:

permissions:
  issues: write

jobs:
  comment-failure:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Get run url
        if: failure()
        run: |
          echo "gha_url=https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}" >> $GITHUB_ENV
          
      - name: Send build failure comment
        if: failure()
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          result-encoding: string
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.number }},
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '<b>Build failure</b> \n\n This pull request contains a build failure which needs addressed [here](${{ env.gha_url}}) .'
            })