name: Generate terraform docs and run go generate
on:
  - pull_request

permissions:
  contents: write  # Needed to update documentation and generated files in the repo
  pull-requests: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Set up Go
      uses: actions/setup-go@v5.0.2
      with:
        go-version-file: 'go.mod'

    - name: Run go generate and commit changes
      run: |
        go generate ./...
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add .
          git commit -m "go generate: automated update"
          git push origin ${{ github.head_ref }}
        else
          echo "No changes detected from go generate"
        fi

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: examples/
        indention: 3
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
    
    - name: Render terraform docs for microsoft365_graph
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: examples/microsoft365_graph
        indention: 3
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
  
    - name: Render terraform docs for microsoft365_graph_beta
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: examples/
        recursive: true
        recursive-path: microsoft365_graph_beta/
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
