name: Generate terraform docs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write  # If you need to update documentation in the repo
  pull-requests: write
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: examples/
        indention: 3
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
    
    - name: Render terraform docs for microsoft365_graph
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: examples/microsoft365_graph
        indention: 3
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
  
    - name: Render terraform docs for microsoft365_graph_beta
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: examples/
        recursive: true
        recursive-path: microsoft365_graph_beta/
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
  
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
      - uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1
        with:
          terraform_version: '1.9.4'
          terraform_wrapper: false.
      - name: git diff
        run: |
          go generate ./...
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "go generate: automated update"
            git push origin ${{ github.head_ref }}
          else
            echo "No changes detected from go generate"
          fi