name: Generate terraform docs

on:
  pull_request:
    branches:
      - main

permissions:
  contents: write  # Required to update documentation in the repo
  pull-requests: write
  
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@e47bfa196e79fa50987ef391be236d9d97b0c786 # v1.2.0
      with:
        working-dir: examples/
        indention: 3
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
    
    - name: Render terraform docs for microsoft365_graph
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: examples/microsoft365_graph
        indention: 3
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"
  
    - name: Render terraform docs for microsoft365_graph_beta
      uses: terraform-docs/gh-actions@v1.2.0
      with:
        working-dir: examples/
        recursive: true
        recursive-path: microsoft365_graph_beta/
        output-file: README.md
        output-method: inject
        git-push: "true"
        git-commit-message: "terraform-docs: automated action"