name: Nightly Acceptance Tests

permissions:
  contents: read

on:
  schedule:
    # Run nightly at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  comprehensive-test:
    name: '🧪 Nightly Test Suite'
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 240
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          
      - name: Check Out  
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          go mod tidy
          go mod download
          
          if ! TF_ACC=0 go test -p 16 -timeout 10m -v -race -coverprofile=coverage.txt -covermode=atomic ./...; then
            echo "Some tests failed, but continuing with coverage upload"
          fi
          
          # Ensure we have some coverage data
          if [ ! -f coverage.txt ] || [ ! -s coverage.txt ]; then
            echo "No coverage data generated, creating minimal coverage file"
            echo "mode: atomic" > coverage.txt
          fi

      - name: Upload unit test coverage to Codecov
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
          flags: unittests
          name: nightly-unit-tests
          fail_ci_if_error: false
          verbose: true

      - name: Run acceptance tests
        env:
          TF_ACC: 1
          M365_TENANT_ID: ${{ secrets.M365_TENANT_ID }}
          M365_CLIENT_ID: ${{ secrets.M365_CLIENT_ID }}
          M365_CLIENT_SECRET: ${{ secrets.M365_CLIENT_SECRET }}
          M365_AUTH_METHOD: client_secret
          M365_CLOUD: public
        run: |
          echo "Running acceptance tests..."
          if [ -z "$M365_TENANT_ID" ]; then
            echo "Acceptance tests skipped - environment variables not configured"
          else
            TF_ACC=1 go test -p 10 -timeout 300m -v -race -coverprofile=acc-coverage.txt -covermode=atomic ./...
          fi

      - name: Upload acceptance test coverage to Codecov
        if: env.M365_TENANT_ID != ''
        uses: codecov/codecov-action@18283e04ce6e62d37312384ff67231eb8fd56d24 # v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./acc-coverage.txt
          flags: acceptancetests
          name: nightly-acceptance-tests
          fail_ci_if_error: false
          verbose: true

      - name: Upload test artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4.4.3
        if: always()
        with:
          name: nightly-test-results
          path: |
            coverage.txt
            acc-coverage.txt
          retention-days: 90

      - name: Create Issue on Failure
        if: failure()
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Nightly Tests Failed - ${new Date().toISOString().split('T')[0]}`,
              body: `The nightly test suite has failed. Check the workflow run for details.`,
              labels: ['bug', 'testing', 'automated']
            });