name: Extract Graph Permissions

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * 0'  # Runs at 00:00 UTC every Sunday

env:
  CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  extract-permissions:
    runs-on: windows-latest  # Using Windows runner for PowerShell
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2

    - name: Install Microsoft Graph PowerShell SDK
      run: |
        Install-Module Microsoft.Graph -Scope CurrentUser -Force
        Import-Module Microsoft.Graph

    - name: Run Graph Permissions Script
      run: |
        ${{ github.workspace }}\scripts\ExportGraphPermissions.ps1 `
          -ClientId $env:CLIENT_ID `
          -ClientSecret $env:CLIENT_SECRET `
          -TenantId $env:TENANT_ID
      shell: pwsh
  
    - name: Move exported file to correct location
      run: |
        $sourceFile = "${{ github.workspace }}\scripts\Export\ExportedGraphPermissions.json"
        $destinationPath = "${{ github.workspace }}\internal\permissions"
        $destinationFile = "ExportedGraphPermissions.json"
        
        # Create the destination directory if it doesn't exist
        New-Item -ItemType Directory -Force -Path $destinationPath
        
        # Move the file
        Move-Item -Path $sourceFile -Destination "$destinationPath\$destinationFile" -Force
      shell: pwsh

    - name: Upload JSON artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: graph-permissions
        path: ${{ github.workspace }}/internal/permissions/ExportedGraphPermissions.json

    # Commit and push if there are changes
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update Graph permissions data
        title: 'Update Graph Permissions Data'
        body: |
          This is an automated pull request to update the Graph permissions data.
          
          Please review the changes and merge if everything looks correct.
        branch: update-graph-permissions
        base: main