name: PR Branch Name Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-branch-name:
    name: Validate Branch Name
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          PATTERN="^([Ff]eat|[Ff]ix|[Dd]ocs|[Ss]tyle|[Rr]efactor|[Tt]est|[Cc]hore|[Bb]uild|[Cc]i|[Pp]erf)-[a-zA-Z0-9._-]+$"
          
          if ! echo "$BRANCH_NAME" | grep -qE "$PATTERN"; then
            echo "ERROR: Branch name '$BRANCH_NAME' does not follow the conventional format."
            echo "Branch names must start with one of: feat-, fix-, docs-, style-, refactor-, test-, chore-, build-, ci-, perf- (or their capitalized versions Feat-, Fix-, etc.)"
            echo "Example: feat-add-new-resource or Feat-add-new-resource"
            exit 1
          fi
          
          echo "Branch name '$BRANCH_NAME' follows the conventional format ✅"