name: PR Branch Name Validation

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-branch-name:
    name: Validate Branch Name
    runs-on: ubuntu-latest
    steps:
      - name: Check Branch Name
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          PATTERN="^(([Ff]eat|[Ff]ix|[Dd]ocs|[Ss]tyle|[Rr]efactor|[Tt]est|[Cc]hore|[Bb]uild|[Cc]i|[Pp]erf)-[a-zA-Z0-9._-]+|dependabot.*)$"
          
          if ! echo "$BRANCH_NAME" | grep -qE "$PATTERN"; then
            echo "❌ ERROR: Invalid branch name format"
            echo ""
            echo "Got branch name: $BRANCH_NAME"
            echo ""
            echo "Branch names must either:"
            echo "1. Start with one of these prefixes (case-insensitive first letter):"
            echo "   - feat-    / Feat-    (for new features)"
            echo "   - fix-     / Fix-     (for bug fixes)"
            echo "   - docs-    / Docs-    (for documentation)"
            echo "   - style-   / Style-   (for formatting)"
            echo "   - refactor-/ Refactor-(for code restructuring)"
            echo "   - test-    / Test-    (for adding tests)"
            echo "   - chore-   / Chore-   (for maintenance)"
            echo "   - build-   / Build-   (for build system)"
            echo "   - ci-      / CI-      (for CI/CD)"
            echo "   - perf-    / Perf-    (for performance)"
            echo ""
            echo "2. OR start with 'dependabot'"
            echo ""
            echo "3. Follow the prefix with alphanumeric characters, dots, or hyphens (except for dependabot branches)"
            echo ""
            echo "Examples:"
            echo "✅ feat-add-new-resource"
            echo "✅ Feat-add-new-resource"
            echo "✅ fix-connection-timeout"
            echo "✅ Fix-connection-timeout"
            echo "✅ dependabot/npm_and_yarn/lodash-4.17.21"
            exit 1
          fi
          
          echo "✅ Branch name '$BRANCH_NAME' follows the conventional format"