name: PR Title Validation

permissions:
  contents: read

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-pr-title:
    name: '✅ Validate PR Title'
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Check PR Title
        run: |
          PR_TITLE="${{ github.event.pull_request.title }}"
          PATTERN="^((feat|fix|docs|style|refactor|test|chore|build|ci|perf)(\(.+\))?: .+|(build|Build)(\(deps\)): Bump .+ from .+ to .+)$"
          
          if ! echo "$PR_TITLE" | grep -qE "$PATTERN"; then
            echo "❌ ERROR: Invalid PR title format"
            echo ""
            echo "Got PR title: $PR_TITLE"
            echo ""
            echo "PR titles must:"
            echo "1. Start with one of these prefixes (lowercase only):"
            echo "   - feat     (for new features)"
            echo "   - fix      (for bug fixes)"
            echo "   - docs     (for documentation)"
            echo "   - style    (for formatting)"
            echo "   - refactor (for code restructuring)"
            echo "   - test     (for adding tests)"
            echo "   - chore    (for maintenance)"
            echo "   - build    (for build system)"
            echo "   - ci       (for CI/CD)"
            echo "   - perf     (for performance)"
            echo ""
            echo "2. Optionally include a scope in parentheses after the type"
            echo ""
            echo "3. Include a description after a colon and space"
            echo ""
            echo "4. OR follow the Dependabot format: Build(deps): Bump [package] from [version] to [version]"
            echo ""
            echo "Examples:"
            echo "✅ feat: add new resource"
            echo "✅ feat(api): add new endpoint"
            echo "✅ fix: resolve connection timeout"
            echo "✅ fix(database): fix query performance"
            echo "✅ Build(deps): Bump github.com/microsoftgraph/msgraph-sdk-go from 1.79.0 to 1.80.0"
            echo ""
            echo "❌ Feat: add new resource (uppercase first letter is not allowed)"
            echo "❌ FIX: resolve issue (uppercase is not allowed)"
            exit 1
          fi
          
          echo "✅ PR title '$PR_TITLE' follows the conventional commit format and is compatible with the release-please"