name: pull request

on:
  workflow_dispatch:
  push:
    branches:
      - 'feat-*'
      - 'fix-*'
      - 'docs-*'
      - 'style-*'
      - 'refactor-*'
      - 'test-*'
      - 'chore-*'
      - 'build-*'
      - 'ci-*'
      - 'perf-*'
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - 'docs/**'

permissions:
  contents: write
  id-token: write
  pull-requests: write
  
jobs:
  branch-check:
    if: github.event_name == 'workflow_dispatch'
    name: "branch check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Extract branch name
        id: extract_branch
        run: echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
        
      - name: Validate Branch Name
        run: |
          branch="${{ steps.extract_branch.outputs.branch }}"
          if [[ "$branch" =~ ^(feat|fix|docs|style|refactor|test|chore|build|ci|perf)- ]]; then
            echo "Success: Branch name '$branch' is valid."
            exit 0
          else
            echo "Error: Branch name must start with 'feat-', 'fix-', 'docs-', 'style-', 'refactor-', 'test-', 'chore-', 'build-', 'ci-', or 'perf-'"
            exit 1
          fi

  call-tests:
    needs: branch-check
    uses: ./.github/workflows/test.yml

  update-pr:
    needs: call-tests
    runs-on: ubuntu-latest
    steps:
      - name: Download test results
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Create or Update PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const branch = context.ref.replace('refs/heads/', '');
            const base = 'main';
            
            // Check if PR already exists
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: `${context.repo.owner}:${branch}`,
              base: base,
              state: 'open'
            });
            
            let pr;
            if (prs.length === 0) {
              // Create new PR
              const { data: newPr } = await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: `[${branch.split('-')[0]}] ${branch.split('-').slice(1).join(' ')}`,
                head: branch,
                base: base,
                body: 'This PR contains changes for the Terraform provider.'
              });
              pr = newPr;
            } else {
              pr = prs[0];
            }
            
            // Prepare PR update content
            const testResults = JSON.parse(fs.readFileSync('test_results.json', 'utf8'));
            
            const prUpdate = `
            ## Test Results
            
            ### Build Status
            ${testResults.buildStatus}
            
            ### Test Status
            ${testResults.testStatus}
            
            ### Test Summary
            ${testResults.testSummary}
            
            ### Coverage Report
            ${testResults.coverageReport}
            
            ${testResults.changedFiles.includes('docs/') ? '### Documentation Changes\nThis PR includes changes to documentation files.' : ''}
            `;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: prUpdate
            });