name: Terraform Provider Checks

on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

jobs:
  # ensure go.mod and go.sum are updated
  depscheck:
    name: Check Dependencies
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - name: Check out code into the Go module directory
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        cache: true
        go-version-file: 'go.mod'
      id: go


    - name: Run 'go mod tidy' and check for differences
      run: |
        go mod tidy
        git diff --exit-code -- go.mod go.sum || \
        (echo; echo "Unexpected difference in go.mod/go.sum files. Run 'go mod tidy' command or revert any go.mod/go.sum changes and commit."; exit 1)

  # ensure the code builds
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
      with:
        egress-policy: audit

    - name: Check out code into the Go module directory
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        cache: true
        go-version-file: 'go.mod'
      id: go

    - name: Get dependencies
      run: |
        go mod download

    - name: Build
      run: |
        go build -v .
  
  linter:
    name: Run tfproviderlint
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Harden Runner
      uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde
      with:
        egress-policy: audit

    - name: Check out code into the Go module directory
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

    - name: Set up Go
      uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
      with:
        cache: true
        go-version-file: 'go.mod'
      id: go

    - name: Debugging Info - Go Version
      run: go version

    - name: Debugging Info - Print Environment Variables
      run: env

    - name: Debugging Info - Print Working Directory
      run: pwd

    - name: Debugging Info - List Files in Current Directory
      run: ls -la

    - name: Install Provider Linter
      run: go install github.com/bflad/tfproviderlint/cmd/tfproviderlint@latest

    - name: Debugging Info - Verify Linter Installation
      run: which tfproviderlint

    - name: Run tfproviderlint
      run: tfproviderlint ./...


  # ensure docs are generated
  gencheck:
    name: Check Generated Docs
    needs: build
    runs-on: ubuntu-latest
    steps:

      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Check out code into the Go module directory
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 2

      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          cache: true
          go-version-file: 'go.mod'
        id: go

      - name: Generate docs and check for differences
        run: |
          go install github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs
          tfplugindocs generate --provider-name microsoft365 --rendered-provider-name "Microsoft 365"
          git diff HEAD --exit-code -- docs/