name: Release Please
run-name: 🚀 Release Please - ${{ github.event.repository.updated_at }}


on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: googleapis/release-please-action@v4.1.3
      with:
        token: ${{ secrets.RELEASE_PLEASE }}
        release-type: go