# cloned from hashicorp and modifed to support ubuntu-latest-m , which provides more disk space
# for go build to complete successfully.
name: Terraform Registry with goreleaser

on:
  workflow_call:
    inputs:
      goreleaser-release-args:
        description: 'goreleaser release Arguments (e.g. --skip-validate)'
        required: false
        type: string
      release-notes:
        description: 'Enable release notes handling (must have previously uploaded artifact named "release-notes" with file "release-notes.txt")'
        required: false
        type: boolean
      setup-go-version:
        description: 'setup-go Go Version'
        required: false
        type: string
      setup-go-version-file:
        description: 'setup-go File From Which To Read Go Version'
        required: false
        type: string
      git-ref:
        description: 'branch, tag or SHA to checkout'
        required: false
        type: string
    secrets:
      gpg-private-key:
        description: 'GPG Private Key'
        required: true
      gpg-private-key-passphrase:
        description: 'GPG Private Key Passphrase'
        required: false

jobs:
  Release:
    runs-on: windows-latest-l
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          ref: ${{ inputs.git-ref }}
          fetch-depth: 0
      - uses: actions/setup-go@v5.1.0 
        with:
          go-version: ${{ inputs.setup-go-version }}
          go-version-file: ${{ inputs.setup-go-version-file }}
          cache: false  # Disable caching to skip the post-cleanup step. saves circa 15 minutes
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6.2.0
        with:
          gpg_private_key: ${{ secrets.gpg-private-key }}
          passphrase: ${{ secrets.gpg-private-key-passphrase }}
      - if: inputs.release-notes != true
        name: goreleaser release (without release notes)
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          args: release --clean ${{ inputs.goreleaser-release-args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
      - if: inputs.release-notes
        id: release-notes-download
        name: Release Notes Download
        uses: actions/download-artifact@v4.1.8
        with:
          name: release-notes
          path: /tmp
      - if: inputs.release-notes
        name: goreleaser release (with release notes)
        uses: goreleaser/goreleaser-action@v6.1.0
        with:
          args: release --release-notes ${{ steps.release-notes-download.outputs.download-path }}/release-notes.txt --clean ${{ inputs.goreleaser-release-args }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
