name: Unit Tests

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    name: '🧪 Run Go Unit Tests'
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 120
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          
      - name: Check Out  
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Run unit tests
        run: |
          echo "Running unit tests..."
          go mod tidy
          go mod download
          
          # Run all unit tests (not acceptance tests)
          TF_ACC=0 go test -v -race ./...
          
      - name: Check for tests
        run: |
          # Ensure there are actual test files in the codebase
          TEST_FILES=$(find . -name "*_test.go" -not -path "./vendor/*" | wc -l)
          if [ "$TEST_FILES" -eq 0 ]; then
            echo "ERROR: No test files found in the codebase"
            exit 1
          fi
          echo "Found $TEST_FILES test files"