name: Unit Tests

permissions:
  contents: read

on:
  pull_request:
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    name: '🧪 Run Go Unit Tests'
    runs-on: ubuntu-24.04-arm
    timeout-minutes: 120
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit
          
      - name: Check Out  
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Get changed Go packages
        id: changed-packages
        run: |
          # Get list of changed .go files
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.go$' || true)
          
          if [ -z "$CHANGED_FILES" ]; then
            echo "No Go files changed"
            echo "packages=" >> $GITHUB_OUTPUT
          else
            echo "Changed Go files:"
            echo "$CHANGED_FILES"
            
            # Extract unique package directories from changed files
            PACKAGES=$(echo "$CHANGED_FILES" | xargs -I {} dirname {} | sort -u | xargs -I {} echo "./{}" | tr '\n' ' ')
            echo "Changed packages: $PACKAGES"
            echo "packages=$PACKAGES" >> $GITHUB_OUTPUT
          fi

      - name: Run tests
        run: |
          PACKAGES="${{ steps.changed-packages.outputs.packages }}"
          if [ -z "$PACKAGES" ]; then
            echo "No Go packages to test"
          else
            echo "Running tests for packages: $PACKAGES"
            go test -v -race -coverprofile=coverage.txt -covermode=atomic $PACKAGES
          fi