name: Unit Tests

on:
  push:
    branches: [ '*' ]
    paths-ignore:
      - '**/*.md'
      - '**/*.yml'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'examples/**'
      - 'website/**'
      - '.vscode/**'
      - '.idea/**'
      - '**/*.txt'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'
      - '.golangci.yml'
      - 'Makefile'
      - 'scripts/**'
      - '.dockerignore'
      - 'Dockerfile'

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-go@v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

        # TODO - setup codecov server side
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v4.5.0
      #   with:
      #     file: ./coverage.txt
      #     flags: unittests
      #     fail_ci_if_error: true
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}