name: Unit Tests

on:
  pull_request:
    branches: [ 'main' ]
    paths-ignore:
      - '**/*.yml'
      - '**/*.md'
      - '**/*.yml'
      - 'LICENSE'
      - '.gitignore'
      - '.editorconfig'
      - 'docs/**'
      - '.github/ISSUE_TEMPLATE/**'
      - 'examples/**'
      - 'website/**'
      - '.vscode/**'
      - '.idea/**'
      - '**/*.txt'
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.svg'
      - '.golangci.yml'
      - 'Makefile'
      - 'scripts/**'
      - '.dockerignore'
      - 'dockerfile'

jobs:
  test:
    name: '🧪 Run Unit Tests'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2.12.0
        with:
          egress-policy: audit
          
      - name: Check Out  
        uses: actions/checkout@v4.2.2

      - uses: actions/setup-go@v5.5.0
        with:
          go-version-file: 'go.mod'
          cache: true
          go-version: stable

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...